from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, Qt)
from PySide6.QtGui import (QAction, QFont)
from PySide6.QtWidgets import (QFrame, QLabel, QMenu, QMenuBar, QPushButton, QStatusBar, QWidget,
                               QMainWindow, QDial)

from gui.assembler_editor import AssemblerEdit
from gui.widgets import RegisterWidget


class EmulatorWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        if not self.objectName():
            self.setObjectName('6502')
        self.resize(1600, 1020)
        self.centralwidget = QWidget(self)
        self.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(self)
        self.setMenuBar(self.menubar)
        self.menuFile = QMenu(self.menubar)
        self.menuView = QMenu(self.menubar)
        self.menuControl = QMenu(self.menubar)
        self.statusbar = QStatusBar(self)
        self.setStatusBar(self.statusbar)

        # Menu
        self.actionHex = QAction(self)
        self.actionHex.setObjectName(u"actionHex")
        self.actionDec = QAction(self)
        self.actionDec.setObjectName(u"actionDec")
        self.actionRun = QAction(self)
        self.actionRun.setObjectName(u"actionRun")
        self.actionStep = QAction(self)
        self.actionStep.setObjectName(u"actionStep")
        self.actionStop = QAction(self)
        self.actionStop.setObjectName(u"actionStop")
        self.actionLoad = QAction(self)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSave = QAction(self)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(self)
        self.actionSave_as.setObjectName(u"actionSave_as")
        # Buttons
        self.run_button = QPushButton(self.centralwidget)
        self.step_button = QPushButton(self.centralwidget)
        self.reset_button = QPushButton(self.centralwidget)
        self.assemble_button = QPushButton(self.centralwidget)
        self.open_file_button = QPushButton(self.centralwidget)
        self.save_file_button = QPushButton(self.centralwidget)
        self.save_file_as_button = QPushButton(self.centralwidget)

        # Fonts
        # Setup fonts
        self.registerFont = QFont("Monospace")
        self.registerFont.setPointSize(15)
        self.registerFont.setStyleHint(QFont.TypeWriter)
        self.memoryRegisterFont = QFont("Monospace")
        self.memoryRegisterFont.setStyleHint(QFont.TypeWriter)
        self.memoryRegisterFont.setPointSize(10)
        self.memory_label_font = QFont()
        self.memory_label_font.setPointSize(12)

        # Frames
        self.computer_frame = QFrame(self.centralwidget)

        self.processor_frame = QFrame(self.computer_frame)
        self.memory_frame = QFrame(self.computer_frame)
        self.zero_page_frame = QFrame(self.computer_frame)
        self.address_register_frame = QFrame(self.computer_frame)
        self.cycle_counter_frame = QFrame(self.computer_frame)
        self.current_instruction_frame = QFrame(self.computer_frame)
        self.stack_frame = QFrame(self.computer_frame)
        self.interrupt_vector_frame = QFrame(self.computer_frame)
        self.nminterrupt_vector_frame = QFrame(self.computer_frame)
        self.reset_vector_frame = QFrame(self.computer_frame)

        self.accumulator_frame = QFrame(self.processor_frame)
        self.alu_frame = QFrame(self.processor_frame)
        self.instruction_register_frame = QFrame(self.processor_frame)
        self.instruction_register_frame = QFrame(self.processor_frame)
        self.index_x_frame = QFrame(self.processor_frame)
        self.index_y_frame = QFrame(self.processor_frame)
        self.program_counter_frame = QFrame(self.processor_frame)
        self.stack_pointer_frame = QFrame(self.processor_frame)
        self.status_register_frame = QFrame(self.processor_frame)
        self.status_register_frame = QFrame(self.processor_frame)

        # Register widgets
        self.accumulator = RegisterWidget(self.accumulator_frame)
        self.accumulator_binary = RegisterWidget(self.accumulator_frame)
        self.address_register_high_byte = RegisterWidget(self.address_register_frame)
        self.address_register_low_byte = RegisterWidget(self.address_register_frame)
        self.alu_op1 = RegisterWidget(self.alu_frame)
        self.alu_op2 = RegisterWidget(self.alu_frame)
        self.alu_res = RegisterWidget(self.alu_frame)
        self.flag_b = RegisterWidget(self.status_register_frame)
        self.flag_c = RegisterWidget(self.status_register_frame)
        self.flag_d = RegisterWidget(self.status_register_frame)
        self.flag_i = RegisterWidget(self.status_register_frame)
        self.flag_n = RegisterWidget(self.status_register_frame)
        self.flag_v = RegisterWidget(self.status_register_frame)
        self.flag_z = RegisterWidget(self.status_register_frame)
        self.index_x = RegisterWidget(self.index_x_frame)
        self.index_y = RegisterWidget(self.index_y_frame)
        self.program_counter_high_byte = RegisterWidget(self.program_counter_frame)
        self.program_counter_low_byte = RegisterWidget(self.program_counter_frame)
        self.stack_pointer = RegisterWidget(self.stack_pointer_frame)
        self.instruction_register = RegisterWidget(self.instruction_register_frame)

        # Labels
        self.accumulator_label = QLabel(self.processor_frame)
        self.address_register_label = QLabel(self.computer_frame)
        self.alu_label = QLabel(self.processor_frame)
        self.alu_operator = QLabel(self.alu_frame)
        self.alu_op1_label = QLabel(self.alu_frame)
        self.alu_op2_label = QLabel(self.alu_frame)
        self.alu_res_label = QLabel(self.alu_frame)
        self.assembler_file_name_label = QLabel(self.centralwidget)
        self.current_instruction = QLabel(self.current_instruction_frame)
        self.instruction_register_label = QLabel(self.processor_frame)
        self.current_instruction_label = QLabel(self.computer_frame)
        self.cycle_counter = QLabel(self.cycle_counter_frame)
        self.cycle_counter_label = QLabel(self.computer_frame)
        self.cycle_stage = QLabel(self.computer_frame)
        self.cycle_stage_label = QLabel(self.computer_frame)
        self.flag_b_label = QLabel(self.status_register_frame)
        self.flag_c_label = QLabel(self.status_register_frame)
        self.flag_d_label = QLabel(self.status_register_frame)
        self.flag_i_label = QLabel(self.status_register_frame)
        self.flag_n_label = QLabel(self.status_register_frame)
        self.flag_v_label = QLabel(self.status_register_frame)
        self.flag_z_label = QLabel(self.status_register_frame)
        self.index_x_label = QLabel(self.processor_frame)
        self.index_y_label = QLabel(self.processor_frame)
        self.interrupt_vector = QLabel(self.interrupt_vector_frame)
        self.interrupt_vector_label = QLabel(self.computer_frame)
        self.memory_label = QLabel(self.computer_frame)
        self.nminterrupt_vector = QLabel(self.nminterrupt_vector_frame)
        self.nminterrupt_vector_label = QLabel(self.computer_frame)
        self.page = QLabel(self.computer_frame)
        self.processor_label = QLabel(self.computer_frame)
        self.program_counter_label = QLabel(self.processor_frame)
        self.reset_vector = QLabel(self.reset_vector_frame)
        self.reset_vector_label = QLabel(self.computer_frame)
        self.stack_label = QLabel(self.computer_frame)
        self.stack_pointer_label = QLabel(self.processor_frame)
        self.status_register_label = QLabel(self.processor_frame)
        self.zero_page_label = QLabel(self.computer_frame)
        self.assembler_input = AssemblerEdit(self.centralwidget)
        self.speed_dial_label = QLabel(self.centralwidget)
        self.speed_min_label = QLabel(self.centralwidget)
        self.speed_max_label = QLabel(self.centralwidget)

        self.zero_page_data = QLabel(self.zero_page_frame)
        self.memory_data = QLabel(self.memory_frame)
        self.stack_data = QLabel(self.stack_pointer_frame)

        self.speed_dial = QDial(self.centralwidget)

    def build_memory_page(self, parent, prefix):
        font1 = QFont()
        font1.setPointSize(13)
        x_0 = 70
        y_0 = 30

        for i in range(0x10):
            setattr(self, f'{prefix}_col_{i:X}', RegisterWidget(parent))
            getattr(self, f'{prefix}_col_{i:X}').setObjectName(u"{prefix}_col_{i:x}")
            getattr(self, f'{prefix}_col_{i:X}').setGeometry(QRect(x_0 + i*30, y_0-20, 30, 20))
            getattr(self, f'{prefix}_col_{i:X}').setFont(font1)
            getattr(self, f'{prefix}_col_{i:X}').setFrameShape(QFrame.Shape.NoFrame)
            getattr(self, f'{prefix}_col_{i:X}').setIndent(8)
            getattr(self, f'{prefix}_col_{i:X}').raise_()

            setattr(self, f'{prefix}_row_{i:X}', RegisterWidget(parent))
            getattr(self, f'{prefix}_row_{i:X}').setObjectName(u"{prefix}_row_{i:x}")
            getattr(self, f'{prefix}_row_{i:X}').setGeometry(QRect(x_0-30, y_0 + i*20, 30, 20))
            getattr(self, f'{prefix}_row_{i:X}').setFont(font1)
            getattr(self, f'{prefix}_row_{i:X}').setFrameShape(QFrame.Shape.NoFrame)
            getattr(self, f'{prefix}_row_{i:X}').setIndent(8)
            getattr(self, f'{prefix}_row_{i:X}').raise_()

        for row in range(0x10):
            for col in range(0x10):
                setattr(self, f'{prefix}_{row:X}{col:X}', RegisterWidget(parent))
                getattr(self, f'{prefix}_{row:X}{col:X}').setObjectName(f'{prefix}_{row:X}{col:X}')
                getattr(self, f'{prefix}_{row:X}{col:X}').setGeometry(QRect(x_0 + col*30, y_0 + row*20, 30, 20))
                getattr(self, f'{prefix}_{row:X}{col:X}').setFont(self.memoryRegisterFont)
                getattr(self, f'{prefix}_{row:X}{col:X}').setFrameShape(QFrame.Shape.StyledPanel)
                getattr(self, f'{prefix}_{row:X}{col:X}').setFrameShadow(QFrame.Shadow.Sunken)
                getattr(self, f'{prefix}_{row:X}{col:X}').setAlignment(
                    Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
                getattr(self, f'{prefix}_{row:X}{col:X}').setIndent(0)
                getattr(self, f'{prefix}_{row:X}{col:X}').raise_()

    def draw_bus_line(self, number, parent, orientation, geometry, style_sheet):
        setattr(self, f'line_{number}', QFrame(parent))
        getattr(self, f'line_{number}').setObjectName(f'line_{number}')
        getattr(self, f'line_{number}').setGeometry(geometry)
        getattr(self, f'line_{number}').setStyleSheet(style_sheet)
        getattr(self, f'line_{number}').setFrameShadow(QFrame.Shadow.Plain)
        getattr(self, f'line_{number}').setLineWidth(5)
        getattr(self, f'line_{number}').setMidLineWidth(0)
        getattr(self, f'line_{number}').setFrameShape(orientation)
        getattr(self, f'line_{number}').raise_()

    def draw_bus_system(self):
        red = 'color: rgb(255, 0, 0);'
        blue = 'color: rgb(0, 85, 255);'
        purple = 'color: rgb(100, 0, 210);'

        # Data bus
        self.draw_bus_line(0, self.computer_frame, QFrame.Shape.HLine, QRect(20, 460, 1241, 20), red)
        self.draw_bus_line(1, self.computer_frame, QFrame.Shape.VLine, QRect(250, 370, 20, 101), red)
        self.draw_bus_line(2, self.computer_frame, QFrame.Shape.VLine, QRect(470, 370, 20, 101), red)
        self.draw_bus_line(3, self.computer_frame, QFrame.Shape.VLine, QRect(600, 470, 20, 111), red)
        self.draw_bus_line(4, self.computer_frame, QFrame.Shape.VLine, QRect(990, 320, 20, 151), red)
        self.draw_bus_line(5, self.computer_frame, QFrame.Shape.VLine, QRect(1230, 470, 20, 111), red)
        # Processor bus
        self.draw_bus_line(6, self.processor_frame, QFrame.Shape.HLine, QRect(10, 300, 681, 20), blue)
        self.draw_bus_line(7, self.processor_frame, QFrame.Shape.VLine, QRect(220, 10, 20, 331), blue)
        self.draw_bus_line(8, self.processor_frame, QFrame.Shape.VLine, QRect(440, 10, 20, 331), blue)
        self.draw_bus_line(9, self.processor_frame, QFrame.Shape.HLine, QRect(190, 160, 151, 20), blue)
        self.draw_bus_line(10, self.processor_frame, QFrame.Shape.HLine, QRect(190, 250, 151, 20), blue)
        self.draw_bus_line(11, self.processor_frame, QFrame.Shape.HLine, QRect(190, 80, 81, 20), blue)
        self.draw_bus_line(12, self.processor_frame, QFrame.Shape.HLine, QRect(450, 80, 41, 20), blue)
        self.draw_bus_line(13, self.processor_frame, QFrame.Shape.HLine, QRect(410, 160, 81, 20), blue)
        self.draw_bus_line(14, self.processor_frame, QFrame.Shape.HLine, QRect(410, 250, 81, 20), blue)
        self.draw_bus_line(15, self.processor_frame, QFrame.Shape.HLine, QRect(410, 40, 81, 20), blue)
        # Address bus
        self.draw_bus_line(16, self.zero_page_frame, QFrame.Shape.HLine, QRect(30, -10, 511, 41), purple)
        self.draw_bus_line(17, self.memory_frame, QFrame.Shape.HLine, QRect(30, -10, 511, 41), purple)
        self.draw_bus_line(18, self.computer_frame, QFrame.Shape.HLine, QRect(20, 400, 281, 41), purple)
        self.draw_bus_line(19, self.computer_frame, QFrame.Shape.HLine, QRect(430, 400, 1051, 41), purple)
        self.draw_bus_line(20, self.computer_frame, QFrame.Shape.VLine, QRect(40, 420, 31, 411), purple)
        self.draw_bus_line(21, self.computer_frame, QFrame.Shape.VLine, QRect(90, 220, 21, 201), purple)
        self.draw_bus_line(22, self.computer_frame, QFrame.Shape.VLine, QRect(670, 420, 31, 411), purple)
        self.draw_bus_line(23, self.computer_frame, QFrame.Shape.VLine, QRect(1030, 370, 31, 51), purple)

    def build_stack_frame(self):
        font6 = QFont()
        font6.setPointSize(14)

        font1 = QFont()
        font1.setPointSize(16)

        self.stack_frame.setObjectName(u"stack_frame")
        self.stack_frame.setGeometry(QRect(960, 30, 151, 341))
        self.stack_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.stack_frame.setFrameShadow(QFrame.Shadow.Plain)
        y_coor = 310
        for i in range(0x10):
            setattr(self, f'stack_{i:X}', QLabel(self.stack_frame))
            getattr(self, f'stack_{i:X}').setObjectName(f'stack_{i:X}')
            getattr(self, f'stack_{i:X}').setGeometry(QRect(100, y_coor - i * 20, 30, 20))
            getattr(self, f'stack_{i:X}').setFont(self.memoryRegisterFont)
            getattr(self, f'stack_{i:X}').setFrameShape(QFrame.Shape.StyledPanel)
            getattr(self, f'stack_{i:X}').setFrameShadow(QFrame.Shadow.Sunken)

            setattr(self, f'stack_sp_{i:X}', QLabel(self.stack_frame))
            getattr(self, f'stack_sp_{i:X}').setObjectName(f"stack_sp_{i:X}")
            getattr(self, f'stack_sp_{i:X}').setGeometry(QRect(50, y_coor - i * 20, 41, 20))
            getattr(self, f'stack_sp_{i:X}').setFont(self.memoryRegisterFont)
            if i == 8:
                getattr(self, f'stack_sp_{i:X}').setStyleSheet(u"color: rgb(230, 0, 80);")
            getattr(self, f'stack_sp_{i:X}').setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)

    def setup(self):
        font2 = QFont()
        font2.setPointSize(22)
        font = QFont()
        font.setPointSize(12)
        font1 = QFont()
        font1.setPointSize(13)
        font3 = QFont()
        font3.setPointSize(20)
        font4 = QFont()
        font4.setPointSize(16)
        font5 = QFont()
        font5.setPointSize(15)

        self.centralwidget.setObjectName(u"centralwidget")

        self.accumulator.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.accumulator.setFrameShadow(QFrame.Shadow.Sunken)
        self.accumulator.setFrameShape(QFrame.Shape.StyledPanel)
        self.accumulator.setGeometry(QRect(10, 10, 51, 31))
        self.accumulator.setFont(self.registerFont)
        self.accumulator.setObjectName(u"accumulator")
        self.accumulator_binary.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.accumulator_binary.setFrameShadow(QFrame.Shadow.Sunken)
        self.accumulator_binary.setFrameShape(QFrame.Shape.StyledPanel)
        self.accumulator_binary.setGeometry(QRect(10, 40, 121, 31))
        self.accumulator_binary.setFont(self.registerFont)
        self.accumulator_binary.setObjectName(u"accumulator_binary")
        self.accumulator_frame.raise_()
        self.accumulator_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.accumulator_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.accumulator_frame.setGeometry(QRect(270, 30, 141, 81))
        self.accumulator_frame.setObjectName(u"accumulator_frame")
        self.accumulator_label.raise_()
        self.accumulator_label.setFont(font)
        self.accumulator_label.setGeometry(QRect(270, 10, 101, 20))
        self.accumulator_label.setObjectName(u"accumulator_label")

        self.address_register_label.raise_()
        self.address_register_label.setFont(font)
        self.address_register_label.setGeometry(QRect(300, 440, 131, 20))
        self.address_register_label.setObjectName(u"address_register")
        self.address_register_frame.raise_()
        self.address_register_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.address_register_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.address_register_frame.setGeometry(QRect(300, 390, 131, 51))
        self.address_register_frame.setObjectName(u"address_register_frame")
        self.address_register_high_byte.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.address_register_high_byte.setFrameShadow(QFrame.Shadow.Sunken)
        self.address_register_high_byte.setFrameShape(QFrame.Shape.StyledPanel)
        self.address_register_high_byte.setGeometry(QRect(10, 10, 51, 31))
        self.address_register_high_byte.setFont(self.registerFont)
        self.address_register_high_byte.setObjectName(u"address_register_high_byte")
        self.address_register_low_byte.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.address_register_low_byte.setFrameShadow(QFrame.Shadow.Sunken)
        self.address_register_low_byte.setFrameShape(QFrame.Shape.StyledPanel)
        self.address_register_low_byte.setGeometry(QRect(70, 10, 51, 31))
        self.address_register_low_byte.setFont(self.registerFont)
        self.address_register_low_byte.setObjectName(u"address_register_low_byte")

        self.alu_frame.raise_()
        self.alu_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.alu_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.alu_frame.setGeometry(QRect(490, 30, 171, 171))
        self.alu_frame.setObjectName(u"alu_frame")
        self.alu_label.raise_()
        self.alu_label.setFont(font)
        self.alu_label.setGeometry(QRect(490, 10, 58, 18))
        self.alu_label.setObjectName(u"alu_label")
        self.alu_op1.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.alu_op1.setFrameShadow(QFrame.Shadow.Sunken)
        self.alu_op1.setFrameShape(QFrame.Shape.StyledPanel)
        self.alu_op1.setGeometry(QRect(10, 10, 51, 31))
        self.alu_op1.setIndent(5)
        self.alu_op1.setFont(self.registerFont)
        self.alu_op1.setObjectName(u"alu_op1")
        self.alu_op1_label.setFont(font)
        self.alu_op1_label.setGeometry(QRect(60, 10, 91, 31))
        self.alu_op1_label.setIndent(5)
        self.alu_op1_label.setObjectName(u"alu_op1_label")
        self.alu_op2.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.alu_op2.setFrameShadow(QFrame.Shadow.Sunken)
        self.alu_op2.setFrameShape(QFrame.Shape.StyledPanel)
        self.alu_op2.setGeometry(QRect(10, 50, 51, 31))
        self.alu_op2.setIndent(5)
        self.alu_op2.setFont(self.registerFont)
        self.alu_op2.setObjectName(u"alu_op2")
        self.alu_op2_label.setFont(font)
        self.alu_op2_label.setGeometry(QRect(60, 50, 91, 31))
        self.alu_op2_label.setIndent(5)
        self.alu_op2_label.setObjectName(u"alu_op2_label")
        self.alu_operator.setFont(font4)
        self.alu_operator.setFrameShadow(QFrame.Shadow.Sunken)
        self.alu_operator.setFrameShape(QFrame.Shape.StyledPanel)
        self.alu_operator.setGeometry(QRect(10, 90, 41, 31))
        self.alu_operator.setObjectName(u"alu_operator")
        self.alu_res.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.alu_res.setFrameShadow(QFrame.Shadow.Sunken)
        self.alu_res.setFrameShape(QFrame.Shape.StyledPanel)
        self.alu_res.setGeometry(QRect(10, 130, 51, 31))
        self.alu_res.setIndent(5)
        self.alu_res.setFont(self.registerFont)
        self.alu_res.setObjectName(u"alu_res")
        self.alu_res_label.setFont(font)
        self.alu_res_label.setGeometry(QRect(60, 130, 51, 31))
        self.alu_res_label.setIndent(5)
        self.alu_res_label.setObjectName(u"alu_res_label")

        self.assemble_button.raise_()
        self.assemble_button.setGeometry(QRect(1230, 20, 70, 40))
        self.assemble_button.setObjectName(u"assemble_button")

        self.assembler_file_name_label.raise_()
        self.assembler_file_name_label.setFont(font)
        self.assembler_file_name_label.setFrameShape(QFrame.Shape.StyledPanel)
        self.assembler_file_name_label.setGeometry(QRect(1320, 70, 250, 31))
        self.assembler_file_name_label.setObjectName(u"assembler_file_name_label")
        self.assembler_input.raise_()
        self.assembler_input.setGeometry(QRect(1320, 110, 250, 811))
        self.assembler_input.setObjectName(u"assembler_input")

        self.build_memory_page(self.memory_frame, 'reg')
        self.build_memory_page(self.zero_page_frame, 'zp')
        self.build_stack_frame()

        self.computer_frame.raise_()
        self.computer_frame.setFrameShadow(QFrame.Shadow.Sunken)
        self.computer_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.computer_frame.setGeometry(QRect(20, 70, 1280, 890))
        self.computer_frame.setLineWidth(3)
        self.instruction_register.setFont(font3)
        self.instruction_register.setFrameShape(QFrame.Shape.StyledPanel)
        self.instruction_register.setGeometry(QRect(10, 10, 51, 31))
        self.instruction_register.setObjectName(u"current_instruction")
        self.instruction_register_frame.raise_()
        self.instruction_register_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.instruction_register_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.instruction_register_frame.setGeometry(QRect(490, 230, 71, 51))
        self.instruction_register_frame.setObjectName(u"current_instruction_frame")
        self.instruction_register_label.raise_()
        self.instruction_register_label.setFont(font)
        self.instruction_register_label.setGeometry(QRect(490, 210, 91, 18))
        self.instruction_register_label.setObjectName(u"current_instruction_label")

        self.cycle_counter.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.cycle_counter.setFont(font3)
        self.cycle_counter.setGeometry(QRect(20, 10, 131, 31))
        self.cycle_counter.setObjectName(u"cycle_counter")
        self.cycle_counter_frame.raise_()
        self.cycle_counter_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.cycle_counter_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.cycle_counter_frame.setGeometry(QRect(760, 110, 171, 51))
        self.cycle_counter_frame.setObjectName(u"cycle_counter_frame")
        self.cycle_counter_label.raise_()
        self.cycle_counter_label.setFont(font)
        self.cycle_counter_label.setGeometry(QRect(760, 90, 58, 18))
        self.cycle_counter_label.setObjectName(u"cycle_counter_label")

        self.cycle_stage.raise_()
        self.cycle_stage.setFont(font3)
        self.cycle_stage.setFrameShadow(QFrame.Shadow.Plain)
        self.cycle_stage.setFrameShape(QFrame.Shape.Box)
        self.cycle_stage.setGeometry(QRect(760, 30, 171, 51))
        self.cycle_stage.setIndent(18)
        self.cycle_stage.setObjectName(u"cycle_stage")
        self.cycle_stage_label.raise_()
        self.cycle_stage_label.setFont(font)
        self.cycle_stage_label.setGeometry(QRect(760, 10, 101, 20))
        self.cycle_stage_label.setObjectName(u"cycle_stage_label")

        self.current_instruction.raise_()
        self.current_instruction.setFont(font3)
        self.current_instruction.setFrameShadow(QFrame.Shadow.Plain)
        self.current_instruction.setFrameShape(QFrame.Shape.Box)
        self.current_instruction.setGeometry(QRect(760, 190, 171, 51))
        # self.current_instruction.setIndent(18)
        self.current_instruction.setObjectName(u"current_instruction")
        self.current_instruction_label.raise_()
        self.current_instruction_label.setFont(font)
        self.current_instruction_label.setGeometry(QRect(760, 200, 101, 20))
        self.current_instruction_label.setObjectName(u"current_instruction_label")


        self.draw_bus_system()

        self.flag_b.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_b.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_b.setGeometry(QRect(70, 40, 15, 30))
        self.flag_b.setIndent(0)
        self.flag_b.setFont(self.registerFont)
        self.flag_b.setObjectName(u"flag_b")
        self.flag_b_label.setAlignment(Qt.AlignCenter)
        self.flag_b_label.setFont(font)
        self.flag_b_label.setGeometry(QRect(70, 10, 15, 30))
        self.flag_b_label.setObjectName(u"flag_b_label")
        self.flag_c.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_c.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_c.setGeometry(QRect(150, 40, 15, 30))
        self.flag_c.setFont(self.registerFont)
        self.flag_c.setIndent(0)
        self.flag_c.setObjectName(u"flag_c")
        self.flag_c_label.setAlignment(Qt.AlignCenter)
        self.flag_c_label.setFont(font)
        self.flag_c_label.setGeometry(QRect(150, 10, 15, 30))
        self.flag_c_label.setObjectName(u"flag_c_label")
        self.flag_d.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_d.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_d.setGeometry(QRect(90, 40, 15, 30))
        self.flag_d.setFont(self.registerFont)
        self.flag_d.setIndent(0)
        self.flag_d.setFont(self.registerFont)
        self.flag_d.setObjectName(u"flag_d")
        self.flag_d_label.setAlignment(Qt.AlignCenter)
        self.flag_d_label.setFont(font)
        self.flag_d_label.setGeometry(QRect(90, 10, 15, 30))
        self.flag_d_label.setObjectName(u"flag_d_label")
        self.flag_i.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_i.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_i.setGeometry(QRect(110, 40, 15, 30))
        self.flag_i.setIndent(0)
        self.flag_i.setFont(self.registerFont)
        self.flag_i.setObjectName(u"flag_i")
        self.flag_i_label.setAlignment(Qt.AlignCenter)
        self.flag_i_label.setFont(font)
        self.flag_i_label.setGeometry(QRect(110, 10, 15, 30))
        self.flag_i_label.setObjectName(u"flag_i_label")
        self.flag_n.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_n.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_n.setGeometry(QRect(10, 40, 15, 30))
        self.flag_n.setIndent(0)
        self.flag_n.setFont(self.registerFont)
        self.flag_n.setObjectName(u"flag_n")
        self.flag_n_label.setAlignment(Qt.AlignCenter)
        self.flag_n_label.setFont(font)
        self.flag_n_label.setGeometry(QRect(10, 10, 15, 30))
        self.flag_n_label.setObjectName(u"flag_n_label")
        self.flag_v.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_v.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_v.setGeometry(QRect(30, 40, 15, 30))
        self.flag_v.setIndent(0)
        self.flag_v.setFont(self.registerFont)
        self.flag_v.setObjectName(u"flag_v")
        self.flag_v_label.setAlignment(Qt.AlignCenter)
        self.flag_v_label.setFont(font)
        self.flag_v_label.setGeometry(QRect(30, 10, 15, 30))
        self.flag_v_label.setObjectName(u"flag_v_label")
        self.flag_z.setFrameShadow(QFrame.Shadow.Sunken)
        self.flag_z.setFrameShape(QFrame.Shape.StyledPanel)
        self.flag_z.setGeometry(QRect(130, 40, 15, 30))
        self.flag_z.setIndent(0)
        self.flag_z.setFont(self.registerFont)
        self.flag_z.setObjectName(u"flag_z")
        self.flag_z_label.setAlignment(Qt.AlignCenter)
        self.flag_z_label.setGeometry(QRect(130, 10, 15, 30))
        self.flag_z_label.setFont(font)
        self.flag_z_label.setObjectName(u"flag_z_label")

        self.index_x.raise_()
        self.index_x.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.index_x.setFrameShadow(QFrame.Shadow.Plain)
        self.index_x.setFrameShape(QFrame.Shape.StyledPanel)
        self.index_x.setGeometry(QRect(10, 10, 51, 31))
        self.index_x.setFont(self.registerFont)
        self.index_x.setObjectName(u"index_x")
        self.index_x_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.index_x_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.index_x_frame.setGeometry(QRect(340, 140, 71, 51))
        self.index_x_frame.setObjectName(u"index_x_frame")
        self.index_x_label.raise_()
        self.index_x_label.setFont(font)
        self.index_x_label.setFont(font)
        self.index_x_label.setGeometry(QRect(350, 120, 61, 20))
        self.index_x_label.setObjectName(u"index_x_label")

        self.index_y.raise_()
        self.index_y.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.index_y.setFrameShape(QFrame.Shape.StyledPanel)
        self.index_y.setGeometry(QRect(10, 10, 51, 31))
        self.index_y.setFont(self.registerFont)
        self.index_y.setObjectName(u"index_y")
        self.index_y_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.index_y_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.index_y_frame.setGeometry(QRect(340, 230, 71, 51))
        self.index_y_frame.setObjectName(u"index_y_frame")
        self.index_y_label.raise_()
        self.index_y_label.setFont(font)
        self.index_y_label.setFont(font)
        self.index_y_label.setGeometry(QRect(350, 210, 61, 20))
        self.index_y_label.setObjectName(u"index_y_label")

        self.interrupt_vector.setFont(font3)
        self.interrupt_vector.setGeometry(QRect(10, 10, 111, 31))
        self.interrupt_vector.setObjectName(u"interrupt_vector")
        self.interrupt_vector_frame.raise_()
        self.interrupt_vector_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.interrupt_vector_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.interrupt_vector_frame.setGeometry(QRect(1130, 30, 131, 51))
        self.interrupt_vector_frame.setObjectName(u"interrupt_vector_frame")
        self.interrupt_vector_label.raise_()
        self.interrupt_vector_label.setFont(font)
        self.interrupt_vector_label.setGeometry(QRect(1130, 10, 131, 20))
        self.interrupt_vector_label.setObjectName(u"interrupt_vector_label")

        self.memory_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.memory_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.memory_frame.setGeometry(QRect(30, 490, 600, 360))
        self.memory_frame.setObjectName(u"memory_frame")
        self.memory_label.raise_()
        self.memory_label.setFont(font)
        self.memory_label.setGeometry(QRect(30, 850, 111, 21))
        self.memory_label.setObjectName(u"memory_label")

        self.nminterrupt_vector.setFont(font3)
        self.nminterrupt_vector.setGeometry(QRect(10, 10, 111, 31))
        self.nminterrupt_vector.setObjectName(u"nminterrupt_vector")
        self.nminterrupt_vector_frame.raise_()
        self.nminterrupt_vector_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.nminterrupt_vector_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.nminterrupt_vector_frame.setGeometry(QRect(1130, 200, 131, 51))
        self.nminterrupt_vector_frame.setObjectName(u"nminterrupt_vector_frame")
        self.nminterrupt_vector_label.raise_()
        self.nminterrupt_vector_label.setFont(font)
        self.nminterrupt_vector_label.setGeometry(QRect(1130, 180, 131, 20))
        self.nminterrupt_vector_label.setObjectName(u"nminterrupt_vector_label")

        self.open_file_button.raise_()
        self.open_file_button.setGeometry(QRect(1320, 20, 70, 40))
        self.open_file_button.setObjectName(u"open_file_button")

        self.page.raise_()
        self.page.setFont(font4)
        self.page.setGeometry(QRect(150, 850, 40, 30))
        self.page.setIndent(5)
        self.page.setMargin(0)
        self.page.setObjectName(u"page")
        self.page.setStyleSheet(u"color: rgb(100, 0, 210);")

        self.processor_frame.raise_()
        self.processor_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.processor_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.processor_frame.setGeometry(QRect(30, 30, 701, 341))
        self.processor_frame.setLineWidth(3)
        self.processor_frame.setMidLineWidth(2)
        self.processor_frame.setObjectName(u"processor_frame")
        self.processor_frame.setStyleSheet(u"color: rgb(0, 0, 127)")
        self.processor_label.raise_()
        self.processor_label.setFont(font)
        self.processor_label.setGeometry(QRect(30, 10, 81, 21))
        self.processor_label.setObjectName(u"processor_label")

        self.program_counter_frame.raise_()
        self.program_counter_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.program_counter_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.program_counter_frame.setGeometry(QRect(60, 140, 131, 51))
        self.program_counter_frame.setObjectName(u"program_counter_frame")
        self.program_counter_high_byte.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.program_counter_high_byte.setFrameShadow(QFrame.Shadow.Sunken)
        self.program_counter_high_byte.setFrameShape(QFrame.Shape.StyledPanel)
        self.program_counter_high_byte.setGeometry(QRect(10, 10, 51, 31))
        self.program_counter_high_byte.setFont(self.registerFont)
        self.program_counter_high_byte.setObjectName(u"program_counter_high_byte")
        self.program_counter_label.raise_()
        self.program_counter_label.setFont(font)
        self.program_counter_label.setFont(font)
        self.program_counter_label.setGeometry(QRect(20, 120, 131, 20))
        self.program_counter_label.setGeometry(QRect(20, 120, 131, 20))
        self.program_counter_label.setObjectName(u"program_counter_label")
        self.program_counter_label.setObjectName(u"program_counter_label")
        self.program_counter_low_byte.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.program_counter_low_byte.setFrameShadow(QFrame.Shadow.Sunken)
        self.program_counter_low_byte.setFrameShape(QFrame.Shape.StyledPanel)
        self.program_counter_low_byte.setGeometry(QRect(70, 10, 51, 31))
        self.program_counter_low_byte.setFont(self.registerFont)
        self.program_counter_low_byte.setObjectName(u"program_counter_low_byte")

        self.reset_button.raise_()
        self.reset_button.setGeometry(QRect(220, 20, 71, 41))
        self.reset_button.setObjectName(u"reset_button")

        self.reset_vector.setFont(font3)
        self.reset_vector.setGeometry(QRect(10, 10, 111, 31))
        self.reset_vector.setObjectName(u"reset_vector")
        self.reset_vector_frame.raise_()
        self.reset_vector_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.reset_vector_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.reset_vector_frame.setGeometry(QRect(1130, 110, 131, 51))
        self.reset_vector_frame.setObjectName(u"reset_vector_frame")
        self.reset_vector_label.raise_()
        self.reset_vector_label.setFont(font)
        self.reset_vector_label.setGeometry(QRect(1130, 90, 131, 20))
        self.reset_vector_label.setObjectName(u"reset_vector_label")

        self.run_button.raise_()
        self.run_button.setGeometry(QRect(20, 20, 71, 41))
        self.run_button.setObjectName(u"run_button")

        self.save_file_as_button.raise_()
        self.save_file_as_button.setGeometry(QRect(1500, 20, 70, 40))
        self.save_file_as_button.setObjectName(u"save_file_as_button")

        self.save_file_button.raise_()
        self.save_file_button.setGeometry(QRect(1410, 20, 70, 40))
        self.save_file_button.setObjectName(u"save_file_button")

        self.stack_frame.raise_()
        self.stack_label.setFont(font)
        self.stack_label.setGeometry(QRect(960, 10, 101, 20))
        self.stack_label.setObjectName(u"stack_label")

        self.stack_pointer.raise_()
        self.stack_pointer.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.stack_pointer.setFrameShadow(QFrame.Shadow.Plain)
        self.stack_pointer.setFrameShape(QFrame.Shape.StyledPanel)
        self.stack_pointer.setGeometry(QRect(10, 10, 51, 31))
        self.stack_pointer.setFont(self.registerFont)
        self.stack_pointer.setObjectName(u"stack_pointer")
        self.stack_pointer_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.stack_pointer_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.stack_pointer_frame.setGeometry(QRect(120, 230, 71, 51))
        self.stack_pointer_frame.setObjectName(u"stack_pointer_frame")
        self.stack_pointer_label.raise_()
        self.stack_pointer_label.setFont(font)
        self.stack_pointer_label.setFont(font)
        self.stack_pointer_label.setGeometry(QRect(90, 210, 101, 20))
        self.stack_pointer_label.setGeometry(QRect(90, 210, 101, 20))
        self.stack_pointer_label.setObjectName(u"stack_pointer_label")
        self.stack_pointer_label.setObjectName(u"stack_pointer_label")

        self.status_register_frame.raise_()
        self.status_register_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.status_register_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.status_register_frame.setGeometry(QRect(20, 30, 171, 81))
        self.status_register_frame.setObjectName(u"status_register_frame")
        self.status_register_label.raise_()
        self.status_register_label.setFont(font)
        self.status_register_label.setGeometry(QRect(20, 10, 141, 21))
        self.status_register_label.setObjectName(u"status_register_label")

        self.step_button.raise_()
        self.step_button.setGeometry(QRect(120, 20, 71, 41))
        self.step_button.setObjectName(u"step_button")

        self.zero_page_frame.raise_()
        self.zero_page_frame.setFrameShadow(QFrame.Shadow.Plain)
        self.zero_page_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.zero_page_frame.setGeometry(QRect(660, 490, 601, 361))
        self.zero_page_frame.setObjectName(u"zero_page_frame")
        self.zero_page_label.raise_()
        self.zero_page_label.setFont(font)
        self.zero_page_label.setGeometry(QRect(660, 850, 81, 21))
        self.zero_page_label.setObjectName(u"zero_page_label")

        self.computer_frame.setObjectName(u"computer_frame")
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1600, 23))
        self.menuFile.setObjectName(u"menuFile")
        self.menuView.setObjectName(u"menuView")
        self.menuControl.setObjectName(u"menuControl")
        self.statusbar.setObjectName(u"statusbar")

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuView.addAction(self.actionHex)
        self.menuView.addAction(self.actionDec)
        self.menuView.addSeparator()
        self.menuControl.addAction(self.actionRun)
        self.menuControl.addAction(self.actionStop)
        self.menuControl.addAction(self.actionStep)
        QMetaObject.connectSlotsByName(self)

        self.speed_dial.setObjectName(u"speed_dial")
        self.speed_dial.setGeometry(QRect(380, 10, 50, 51))
        self.speed_dial_label.setObjectName(u"speed_dial_label")
        self.speed_dial_label.setGeometry(QRect(310, 30, 51, 20))
        font7 = QFont()
        font7.setPointSize(11)
        self.speed_dial_label.setFont(font7)
        self.speed_min_label.setObjectName(u"speed_min_label")
        self.speed_min_label.setGeometry(QRect(357, 40, 31, 20))
        self.speed_min_label.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.speed_min_label.setIndent(0)
        self.speed_max_label.setObjectName(u"speed_max_label")
        self.speed_max_label.setGeometry(QRect(420, 40, 31, 20))
        self.speed_max_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.speed_max_label.setIndent(2)
        self.speed_dial.raise_()
        self.speed_dial_label.raise_()
        self.speed_min_label.raise_()
        self.speed_max_label.raise_()

    def retranslate(self):
        self.setWindowTitle(QCoreApplication.translate("MainWindow", u"6502 Emulator", None))
        self.actionHex.setText(QCoreApplication.translate("MainWindow", u"Hex", None))
        self.actionDec.setText(QCoreApplication.translate("MainWindow", u"Dec", None))
        self.actionRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.actionStep.setText(QCoreApplication.translate("MainWindow", u"Step", None))
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load ...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as ...", None))
        for i in range(0x10):
            getattr(self, f'reg_col_{i:X}').setText(QCoreApplication.translate("MainWindow", f'{i:X}', None))
            getattr(self, f'reg_row_{i:X}').setText(QCoreApplication.translate("MainWindow", f'{i:X}', None))
            getattr(self, f'zp_col_{i:X}').setText(QCoreApplication.translate("MainWindow", f'{i:X}', None))
            getattr(self, f'zp_row_{i:X}').setText(QCoreApplication.translate("MainWindow", f'{i:X}', None))
        for i in range(0x100):
            getattr(self, f'reg_{i:02X}').setText(QCoreApplication.translate("MainWindow", '0', None))
            getattr(self, f'zp_{i:02X}').setText(QCoreApplication.translate("MainWindow", '0', None))

        self.page.setText(QCoreApplication.translate("MainWindow", u"FF", None))
        self.cycle_counter.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.cycle_counter_label.setText(QCoreApplication.translate("MainWindow", u"Cycles", None))
        self.index_y.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.index_x.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.accumulator_binary.setText(QCoreApplication.translate("MainWindow", u"00000000", None))
        self.accumulator.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.program_counter_high_byte.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.program_counter_low_byte.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.flag_c.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.flag_z.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.flag_d.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.flag_b.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.flag_v.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.flag_n.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.flag_i.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.flag_n_label.setText(QCoreApplication.translate("MainWindow", u"N", None))
        self.flag_v_label.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.flag_b_label.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.flag_d_label.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.flag_i_label.setText(QCoreApplication.translate("MainWindow", u"I", None))
        self.flag_z_label.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.flag_c_label.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.status_register_label.setText(QCoreApplication.translate("MainWindow", u"Status Register", None))
        self.program_counter_label.setText(QCoreApplication.translate("MainWindow", u"Program Counter", None))
        self.accumulator_label.setText(QCoreApplication.translate("MainWindow", u"Accumulator", None))
        self.index_x_label.setText(QCoreApplication.translate("MainWindow", u"Index X", None))
        self.index_y_label.setText(QCoreApplication.translate("MainWindow", u"Index Y", None))
        self.stack_pointer_label.setText(QCoreApplication.translate("MainWindow", u"Stack Pointer", None))
        self.stack_pointer.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.instruction_register.setText("")
        self.instruction_register_label.setText(QCoreApplication.translate("MainWindow", u"Instruction", None))
        self.alu_operator.setText(QCoreApplication.translate("MainWindow", u"op", None))
        self.alu_op1.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.alu_op2.setText(QCoreApplication.translate("MainWindow", u"00", None))
        self.alu_res.setText(QCoreApplication.translate("MainWindow", u"255", None))
        self.alu_op1_label.setText(QCoreApplication.translate("MainWindow", u"Operand 1", None))
        self.alu_op2_label.setText(QCoreApplication.translate("MainWindow", u"Operand 2", None))
        self.alu_res_label.setText(QCoreApplication.translate("MainWindow", u"Result", None))
        self.alu_label.setText(QCoreApplication.translate("MainWindow", u"ALU", None))
        self.address_register_high_byte.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.address_register_low_byte.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.address_register_label.setText(QCoreApplication.translate("MainWindow", u"Address Register", None))
        self.cycle_stage.setText(QCoreApplication.translate("MainWindow", u"stage", None))
        self.current_instruction.setText(QCoreApplication.translate("MainWindow", u"Current instruction", None))
        self.zero_page_label.setText(QCoreApplication.translate("MainWindow", u"Zero Page", None))
        for i in range(0x10):
            getattr(self, f'stack_{i:X}').setText(QCoreApplication.translate("MainWindow", '0', None))
            getattr(self, f'stack_sp_{i:X}').setText(QCoreApplication.translate("MainWindow", '', None))
        self.memory_label.setText(QCoreApplication.translate("MainWindow", u"Memory Page", None))
        self.stack_label.setText(QCoreApplication.translate("MainWindow", u"Stack", None))
        self.cycle_stage_label.setText(QCoreApplication.translate("MainWindow", u"Cycle Stage", None))
        self.processor_label.setText(QCoreApplication.translate("MainWindow", u"CPU", None))
        self.run_button.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.step_button.setText(QCoreApplication.translate("MainWindow", u"Step", None))
        self.reset_button.setText(QCoreApplication.translate("MainWindow", u"Reset", None))
        self.assemble_button.setText(QCoreApplication.translate("MainWindow", u"Assemble", None))
        self.open_file_button.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.save_file_button.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.save_file_as_button.setText(QCoreApplication.translate("MainWindow", u"Save as...", None))
        self.assembler_file_name_label.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuControl.setTitle(QCoreApplication.translate("MainWindow", u"Control", None))
        self.speed_dial_label.setText(QCoreApplication.translate("MainWindow", u"Speed", None))
        self.speed_min_label.setText(QCoreApplication.translate("MainWindow", u"min", None))
        self.speed_max_label.setText(QCoreApplication.translate("MainWindow", u"max", None))
