# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLCDNumber, QLabel,
    QMainWindow, QMenu, QMenuBar, QSizePolicy,
    QStatusBar, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 840)
        self.actionHex = QAction(MainWindow)
        self.actionHex.setObjectName(u"actionHex")
        self.actionDec = QAction(MainWindow)
        self.actionDec.setObjectName(u"actionDec")
        self.actionRun = QAction(MainWindow)
        self.actionRun.setObjectName(u"actionRun")
        self.actionStep = QAction(MainWindow)
        self.actionStep.setObjectName(u"actionStep")
        self.actionStop = QAction(MainWindow)
        self.actionStop.setObjectName(u"actionStop")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSave_as = QAction(MainWindow)
        self.actionSave_as.setObjectName(u"actionSave_as")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.simulator = QFrame(self.centralwidget)
        self.simulator.setObjectName(u"simulator")
        self.simulator.setGeometry(QRect(10, 10, 800, 780))
        self.simulator.setFrameShape(QFrame.StyledPanel)
        self.simulator.setFrameShadow(QFrame.Raised)
        self.index_x = QLCDNumber(self.simulator)
        self.index_x.setObjectName(u"index_x")
        self.index_x.setGeometry(QRect(260, 170, 51, 31))
        self.index_x.setDigitCount(3)
        self.index_x.setMode(QLCDNumber.Hex)
        self.index_x.setProperty("intValue", 255)
        self.index_y = QLCDNumber(self.simulator)
        self.index_y.setObjectName(u"index_y")
        self.index_y.setGeometry(QRect(260, 230, 51, 31))
        self.index_y.setDigitCount(3)
        self.index_y.setMode(QLCDNumber.Hex)
        self.index_y.setProperty("intValue", 255)
        self.stack_pointer = QLCDNumber(self.simulator)
        self.stack_pointer.setObjectName(u"stack_pointer")
        self.stack_pointer.setGeometry(QRect(670, 60, 51, 31))
        self.stack_pointer.setDigitCount(3)
        self.stack_pointer.setMode(QLCDNumber.Hex)
        self.stack_pointer.setProperty("intValue", 255)
        self.label_3 = QLabel(self.simulator)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(670, 40, 101, 20))
        font = QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_5 = QLabel(self.simulator)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(260, 150, 61, 20))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.simulator)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(260, 210, 61, 20))
        self.label_6.setFont(font)
        self.program_counter = QFrame(self.simulator)
        self.program_counter.setObjectName(u"program_counter")
        self.program_counter.setGeometry(QRect(50, 200, 141, 51))
        self.program_counter.setFrameShape(QFrame.StyledPanel)
        self.program_counter.setFrameShadow(QFrame.Raised)
        self.program_counter_high_byte = QLCDNumber(self.program_counter)
        self.program_counter_high_byte.setObjectName(u"program_counter_high_byte")
        self.program_counter_high_byte.setGeometry(QRect(10, 10, 51, 31))
        self.program_counter_high_byte.setDigitCount(3)
        self.program_counter_high_byte.setMode(QLCDNumber.Hex)
        self.program_counter_high_byte.setProperty("intValue", 255)
        self.program_counter_low_byte = QLCDNumber(self.program_counter)
        self.program_counter_low_byte.setObjectName(u"program_counter_low_byte")
        self.program_counter_low_byte.setGeometry(QRect(70, 10, 51, 31))
        self.program_counter_low_byte.setDigitCount(3)
        self.program_counter_low_byte.setMode(QLCDNumber.Hex)
        self.program_counter_low_byte.setProperty("intValue", 255)
        self.memory = QFrame(self.simulator)
        self.memory.setObjectName(u"memory")
        self.memory.setGeometry(QRect(50, 370, 701, 361))
        self.memory.setFrameShape(QFrame.StyledPanel)
        self.memory.setFrameShadow(QFrame.Raised)
        self.label_page = QLabel(self.memory)
        self.label_page.setObjectName(u"label_page")
        self.label_page.setGeometry(QRect(20, 150, 51, 20))
        self.label_page.setFont(font)
        self.label_data = QLabel(self.memory)
        self.label_data.setObjectName(u"label_data")
        self.label_data.setGeometry(QRect(620, 150, 41, 20))
        self.label_data.setFont(font)
        self.page_col_0 = QLabel(self.memory)
        self.page_col_0.setObjectName(u"page_col_0")
        self.page_col_0.setGeometry(QRect(109, 10, 31, 20))
        font1 = QFont()
        font1.setFamilies([u"Noto Mono"])
        font1.setPointSize(14)
        self.page_col_0.setFont(font1)
        self.page_col_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_0.setIndent(5)
        self.reg00 = QLCDNumber(self.memory)
        self.reg00.setObjectName(u"reg00")
        self.reg00.setGeometry(QRect(110, 30, 30, 20))
        self.reg00.setDigitCount(3)
        self.reg00.setMode(QLCDNumber.Dec)
        self.reg00.setProperty("intValue", 255)
        self.reg22 = QLCDNumber(self.memory)
        self.reg22.setObjectName(u"reg22")
        self.reg22.setGeometry(QRect(170, 70, 30, 20))
        self.reg22.setDigitCount(3)
        self.reg22.setMode(QLCDNumber.Hex)
        self.reg22.setProperty("intValue", 255)
        self.reg81 = QLCDNumber(self.memory)
        self.reg81.setObjectName(u"reg81")
        self.reg81.setGeometry(QRect(140, 190, 30, 20))
        self.reg81.setDigitCount(3)
        self.reg81.setMode(QLCDNumber.Hex)
        self.reg81.setProperty("intValue", 255)
        self.reg82 = QLCDNumber(self.memory)
        self.reg82.setObjectName(u"reg82")
        self.reg82.setGeometry(QRect(170, 190, 30, 20))
        self.reg82.setDigitCount(3)
        self.reg82.setMode(QLCDNumber.Hex)
        self.reg82.setProperty("intValue", 255)
        self.reg91 = QLCDNumber(self.memory)
        self.reg91.setObjectName(u"reg91")
        self.reg91.setGeometry(QRect(140, 210, 30, 20))
        self.reg91.setDigitCount(3)
        self.reg91.setMode(QLCDNumber.Hex)
        self.reg91.setProperty("intValue", 255)
        self.reg73 = QLCDNumber(self.memory)
        self.reg73.setObjectName(u"reg73")
        self.reg73.setGeometry(QRect(200, 170, 30, 20))
        self.reg73.setDigitCount(3)
        self.reg73.setMode(QLCDNumber.Hex)
        self.reg73.setProperty("intValue", 255)
        self.reg63 = QLCDNumber(self.memory)
        self.reg63.setObjectName(u"reg63")
        self.reg63.setGeometry(QRect(200, 150, 30, 20))
        self.reg63.setDigitCount(3)
        self.reg63.setMode(QLCDNumber.Hex)
        self.reg63.setProperty("intValue", 255)
        self.regD1 = QLCDNumber(self.memory)
        self.regD1.setObjectName(u"regD1")
        self.regD1.setGeometry(QRect(140, 290, 30, 20))
        self.regD1.setDigitCount(3)
        self.regD1.setMode(QLCDNumber.Hex)
        self.regD1.setProperty("intValue", 255)
        self.reg30 = QLCDNumber(self.memory)
        self.reg30.setObjectName(u"reg30")
        self.reg30.setGeometry(QRect(110, 90, 30, 20))
        self.reg30.setDigitCount(3)
        self.reg30.setMode(QLCDNumber.Hex)
        self.reg30.setProperty("intValue", 255)
        self.reg40 = QLCDNumber(self.memory)
        self.reg40.setObjectName(u"reg40")
        self.reg40.setGeometry(QRect(110, 110, 30, 20))
        self.reg40.setDigitCount(3)
        self.reg40.setMode(QLCDNumber.Hex)
        self.reg40.setProperty("intValue", 255)
        self.reg52 = QLCDNumber(self.memory)
        self.reg52.setObjectName(u"reg52")
        self.reg52.setGeometry(QRect(170, 130, 30, 20))
        self.reg52.setDigitCount(3)
        self.reg52.setMode(QLCDNumber.Hex)
        self.reg52.setProperty("intValue", 255)
        self.reg51 = QLCDNumber(self.memory)
        self.reg51.setObjectName(u"reg51")
        self.reg51.setGeometry(QRect(140, 130, 30, 20))
        self.reg51.setDigitCount(3)
        self.reg51.setMode(QLCDNumber.Hex)
        self.reg51.setProperty("intValue", 255)
        self.reg72 = QLCDNumber(self.memory)
        self.reg72.setObjectName(u"reg72")
        self.reg72.setGeometry(QRect(170, 170, 30, 20))
        self.reg72.setDigitCount(3)
        self.reg72.setMode(QLCDNumber.Hex)
        self.reg72.setProperty("intValue", 255)
        self.regB1 = QLCDNumber(self.memory)
        self.regB1.setObjectName(u"regB1")
        self.regB1.setGeometry(QRect(140, 250, 30, 20))
        self.regB1.setDigitCount(3)
        self.regB1.setMode(QLCDNumber.Hex)
        self.regB1.setProperty("intValue", 255)
        self.regC2 = QLCDNumber(self.memory)
        self.regC2.setObjectName(u"regC2")
        self.regC2.setGeometry(QRect(170, 270, 30, 20))
        self.regC2.setDigitCount(3)
        self.regC2.setMode(QLCDNumber.Hex)
        self.regC2.setProperty("intValue", 255)
        self.regE3 = QLCDNumber(self.memory)
        self.regE3.setObjectName(u"regE3")
        self.regE3.setGeometry(QRect(200, 310, 30, 20))
        self.regE3.setDigitCount(3)
        self.regE3.setMode(QLCDNumber.Hex)
        self.regE3.setProperty("intValue", 255)
        self.regB3 = QLCDNumber(self.memory)
        self.regB3.setObjectName(u"regB3")
        self.regB3.setGeometry(QRect(200, 250, 30, 20))
        self.regB3.setDigitCount(3)
        self.regB3.setMode(QLCDNumber.Hex)
        self.regB3.setProperty("intValue", 255)
        self.regB2 = QLCDNumber(self.memory)
        self.regB2.setObjectName(u"regB2")
        self.regB2.setGeometry(QRect(170, 250, 30, 20))
        self.regB2.setDigitCount(3)
        self.regB2.setMode(QLCDNumber.Hex)
        self.regB2.setProperty("intValue", 255)
        self.reg70 = QLCDNumber(self.memory)
        self.reg70.setObjectName(u"reg70")
        self.reg70.setGeometry(QRect(110, 170, 30, 20))
        self.reg70.setDigitCount(3)
        self.reg70.setMode(QLCDNumber.Hex)
        self.reg70.setProperty("intValue", 255)
        self.regA3 = QLCDNumber(self.memory)
        self.regA3.setObjectName(u"regA3")
        self.regA3.setGeometry(QRect(200, 230, 30, 20))
        self.regA3.setDigitCount(3)
        self.regA3.setMode(QLCDNumber.Hex)
        self.regA3.setProperty("intValue", 255)
        self.reg13 = QLCDNumber(self.memory)
        self.reg13.setObjectName(u"reg13")
        self.reg13.setGeometry(QRect(200, 50, 30, 20))
        self.reg13.setDigitCount(3)
        self.reg13.setMode(QLCDNumber.Hex)
        self.reg13.setProperty("intValue", 255)
        self.reg60 = QLCDNumber(self.memory)
        self.reg60.setObjectName(u"reg60")
        self.reg60.setGeometry(QRect(110, 150, 30, 20))
        self.reg60.setDigitCount(3)
        self.reg60.setMode(QLCDNumber.Hex)
        self.reg60.setProperty("intValue", 255)
        self.regA1 = QLCDNumber(self.memory)
        self.regA1.setObjectName(u"regA1")
        self.regA1.setGeometry(QRect(140, 230, 30, 20))
        self.regA1.setDigitCount(3)
        self.regA1.setMode(QLCDNumber.Hex)
        self.regA1.setProperty("intValue", 255)
        self.reg41 = QLCDNumber(self.memory)
        self.reg41.setObjectName(u"reg41")
        self.reg41.setGeometry(QRect(140, 110, 30, 20))
        self.reg41.setDigitCount(3)
        self.reg41.setMode(QLCDNumber.Hex)
        self.reg41.setProperty("intValue", 255)
        self.regD3 = QLCDNumber(self.memory)
        self.regD3.setObjectName(u"regD3")
        self.regD3.setGeometry(QRect(200, 290, 30, 20))
        self.regD3.setDigitCount(3)
        self.regD3.setMode(QLCDNumber.Hex)
        self.regD3.setProperty("intValue", 255)
        self.regC0 = QLCDNumber(self.memory)
        self.regC0.setObjectName(u"regC0")
        self.regC0.setGeometry(QRect(110, 270, 30, 20))
        self.regC0.setDigitCount(3)
        self.regC0.setMode(QLCDNumber.Hex)
        self.regC0.setProperty("intValue", 255)
        self.regA0 = QLCDNumber(self.memory)
        self.regA0.setObjectName(u"regA0")
        self.regA0.setGeometry(QRect(110, 230, 30, 20))
        self.regA0.setDigitCount(3)
        self.regA0.setMode(QLCDNumber.Hex)
        self.regA0.setProperty("intValue", 255)
        self.regF1 = QLCDNumber(self.memory)
        self.regF1.setObjectName(u"regF1")
        self.regF1.setGeometry(QRect(140, 330, 30, 20))
        self.regF1.setDigitCount(3)
        self.regF1.setMode(QLCDNumber.Hex)
        self.regF1.setProperty("intValue", 255)
        self.regD0 = QLCDNumber(self.memory)
        self.regD0.setObjectName(u"regD0")
        self.regD0.setGeometry(QRect(110, 290, 30, 20))
        self.regD0.setDigitCount(3)
        self.regD0.setMode(QLCDNumber.Hex)
        self.regD0.setProperty("intValue", 255)
        self.reg50 = QLCDNumber(self.memory)
        self.reg50.setObjectName(u"reg50")
        self.reg50.setGeometry(QRect(110, 130, 30, 20))
        self.reg50.setDigitCount(3)
        self.reg50.setMode(QLCDNumber.Hex)
        self.reg50.setProperty("intValue", 255)
        self.reg23 = QLCDNumber(self.memory)
        self.reg23.setObjectName(u"reg23")
        self.reg23.setGeometry(QRect(200, 70, 30, 20))
        self.reg23.setDigitCount(3)
        self.reg23.setMode(QLCDNumber.Hex)
        self.reg23.setProperty("intValue", 255)
        self.regD2 = QLCDNumber(self.memory)
        self.regD2.setObjectName(u"regD2")
        self.regD2.setGeometry(QRect(170, 290, 30, 20))
        self.regD2.setDigitCount(3)
        self.regD2.setMode(QLCDNumber.Hex)
        self.regD2.setProperty("intValue", 255)
        self.reg12 = QLCDNumber(self.memory)
        self.reg12.setObjectName(u"reg12")
        self.reg12.setGeometry(QRect(170, 50, 30, 20))
        self.reg12.setDigitCount(3)
        self.reg12.setMode(QLCDNumber.Hex)
        self.reg12.setProperty("intValue", 255)
        self.reg02 = QLCDNumber(self.memory)
        self.reg02.setObjectName(u"reg02")
        self.reg02.setGeometry(QRect(170, 30, 31, 20))
        self.reg02.setDigitCount(3)
        self.reg02.setMode(QLCDNumber.Hex)
        self.reg02.setProperty("intValue", 255)
        self.regA2 = QLCDNumber(self.memory)
        self.regA2.setObjectName(u"regA2")
        self.regA2.setGeometry(QRect(170, 230, 30, 20))
        self.regA2.setDigitCount(3)
        self.regA2.setMode(QLCDNumber.Hex)
        self.regA2.setProperty("intValue", 255)
        self.reg90 = QLCDNumber(self.memory)
        self.reg90.setObjectName(u"reg90")
        self.reg90.setGeometry(QRect(110, 210, 30, 20))
        self.reg90.setDigitCount(3)
        self.reg90.setMode(QLCDNumber.Hex)
        self.reg90.setProperty("intValue", 255)
        self.reg83 = QLCDNumber(self.memory)
        self.reg83.setObjectName(u"reg83")
        self.reg83.setGeometry(QRect(200, 190, 30, 20))
        self.reg83.setDigitCount(3)
        self.reg83.setMode(QLCDNumber.Hex)
        self.reg83.setProperty("intValue", 255)
        self.reg31 = QLCDNumber(self.memory)
        self.reg31.setObjectName(u"reg31")
        self.reg31.setGeometry(QRect(140, 90, 30, 20))
        self.reg31.setDigitCount(3)
        self.reg31.setMode(QLCDNumber.Hex)
        self.reg31.setProperty("intValue", 255)
        self.reg93 = QLCDNumber(self.memory)
        self.reg93.setObjectName(u"reg93")
        self.reg93.setGeometry(QRect(200, 210, 30, 20))
        self.reg93.setDigitCount(3)
        self.reg93.setMode(QLCDNumber.Hex)
        self.reg93.setProperty("intValue", 255)
        self.reg42 = QLCDNumber(self.memory)
        self.reg42.setObjectName(u"reg42")
        self.reg42.setGeometry(QRect(170, 110, 30, 20))
        self.reg42.setDigitCount(3)
        self.reg42.setMode(QLCDNumber.Hex)
        self.reg42.setProperty("intValue", 255)
        self.regC3 = QLCDNumber(self.memory)
        self.regC3.setObjectName(u"regC3")
        self.regC3.setGeometry(QRect(200, 270, 30, 20))
        self.regC3.setDigitCount(3)
        self.regC3.setMode(QLCDNumber.Hex)
        self.regC3.setProperty("intValue", 255)
        self.reg03 = QLCDNumber(self.memory)
        self.reg03.setObjectName(u"reg03")
        self.reg03.setGeometry(QRect(200, 30, 30, 20))
        self.reg03.setDigitCount(3)
        self.reg03.setMode(QLCDNumber.Hex)
        self.reg03.setProperty("intValue", 255)
        self.regC1 = QLCDNumber(self.memory)
        self.regC1.setObjectName(u"regC1")
        self.regC1.setGeometry(QRect(140, 270, 30, 20))
        self.regC1.setDigitCount(3)
        self.regC1.setMode(QLCDNumber.Hex)
        self.regC1.setProperty("intValue", 255)
        self.regE1 = QLCDNumber(self.memory)
        self.regE1.setObjectName(u"regE1")
        self.regE1.setGeometry(QRect(140, 310, 30, 20))
        self.regE1.setDigitCount(3)
        self.regE1.setMode(QLCDNumber.Hex)
        self.regE1.setProperty("intValue", 255)
        self.reg01 = QLCDNumber(self.memory)
        self.reg01.setObjectName(u"reg01")
        self.reg01.setGeometry(QRect(140, 30, 30, 20))
        self.reg01.setDigitCount(3)
        self.reg01.setMode(QLCDNumber.Hex)
        self.reg01.setProperty("intValue", 255)
        self.reg53 = QLCDNumber(self.memory)
        self.reg53.setObjectName(u"reg53")
        self.reg53.setGeometry(QRect(200, 130, 30, 20))
        self.reg53.setDigitCount(3)
        self.reg53.setMode(QLCDNumber.Hex)
        self.reg53.setProperty("intValue", 255)
        self.reg80 = QLCDNumber(self.memory)
        self.reg80.setObjectName(u"reg80")
        self.reg80.setGeometry(QRect(110, 190, 30, 20))
        self.reg80.setDigitCount(3)
        self.reg80.setMode(QLCDNumber.Hex)
        self.reg80.setProperty("intValue", 255)
        self.regF0 = QLCDNumber(self.memory)
        self.regF0.setObjectName(u"regF0")
        self.regF0.setGeometry(QRect(110, 330, 30, 20))
        self.regF0.setDigitCount(3)
        self.regF0.setMode(QLCDNumber.Hex)
        self.regF0.setProperty("intValue", 255)
        self.regF3 = QLCDNumber(self.memory)
        self.regF3.setObjectName(u"regF3")
        self.regF3.setGeometry(QRect(200, 330, 30, 20))
        self.regF3.setDigitCount(3)
        self.regF3.setMode(QLCDNumber.Hex)
        self.regF3.setProperty("intValue", 255)
        self.reg20 = QLCDNumber(self.memory)
        self.reg20.setObjectName(u"reg20")
        self.reg20.setGeometry(QRect(110, 70, 30, 20))
        self.reg20.setDigitCount(3)
        self.reg20.setMode(QLCDNumber.Hex)
        self.reg20.setProperty("intValue", 255)
        self.reg92 = QLCDNumber(self.memory)
        self.reg92.setObjectName(u"reg92")
        self.reg92.setGeometry(QRect(170, 210, 30, 20))
        self.reg92.setDigitCount(3)
        self.reg92.setMode(QLCDNumber.Hex)
        self.reg92.setProperty("intValue", 255)
        self.reg21 = QLCDNumber(self.memory)
        self.reg21.setObjectName(u"reg21")
        self.reg21.setGeometry(QRect(140, 70, 30, 20))
        self.reg21.setDigitCount(3)
        self.reg21.setMode(QLCDNumber.Hex)
        self.reg21.setProperty("intValue", 255)
        self.reg71 = QLCDNumber(self.memory)
        self.reg71.setObjectName(u"reg71")
        self.reg71.setGeometry(QRect(140, 170, 30, 20))
        self.reg71.setDigitCount(3)
        self.reg71.setMode(QLCDNumber.Hex)
        self.reg71.setProperty("intValue", 255)
        self.reg33 = QLCDNumber(self.memory)
        self.reg33.setObjectName(u"reg33")
        self.reg33.setGeometry(QRect(200, 90, 30, 20))
        self.reg33.setDigitCount(3)
        self.reg33.setMode(QLCDNumber.Hex)
        self.reg33.setProperty("intValue", 255)
        self.regE2 = QLCDNumber(self.memory)
        self.regE2.setObjectName(u"regE2")
        self.regE2.setGeometry(QRect(170, 310, 30, 20))
        self.regE2.setDigitCount(3)
        self.regE2.setMode(QLCDNumber.Hex)
        self.regE2.setProperty("intValue", 255)
        self.regB0 = QLCDNumber(self.memory)
        self.regB0.setObjectName(u"regB0")
        self.regB0.setGeometry(QRect(110, 250, 30, 20))
        self.regB0.setDigitCount(3)
        self.regB0.setMode(QLCDNumber.Hex)
        self.regB0.setProperty("intValue", 255)
        self.reg62 = QLCDNumber(self.memory)
        self.reg62.setObjectName(u"reg62")
        self.reg62.setGeometry(QRect(170, 150, 30, 20))
        self.reg62.setDigitCount(3)
        self.reg62.setMode(QLCDNumber.Hex)
        self.reg62.setProperty("intValue", 255)
        self.reg61 = QLCDNumber(self.memory)
        self.reg61.setObjectName(u"reg61")
        self.reg61.setGeometry(QRect(140, 150, 30, 20))
        self.reg61.setDigitCount(3)
        self.reg61.setMode(QLCDNumber.Hex)
        self.reg61.setProperty("intValue", 255)
        self.reg43 = QLCDNumber(self.memory)
        self.reg43.setObjectName(u"reg43")
        self.reg43.setGeometry(QRect(200, 110, 30, 20))
        self.reg43.setDigitCount(3)
        self.reg43.setMode(QLCDNumber.Hex)
        self.reg43.setProperty("intValue", 255)
        self.regF2 = QLCDNumber(self.memory)
        self.regF2.setObjectName(u"regF2")
        self.regF2.setGeometry(QRect(170, 330, 30, 20))
        self.regF2.setDigitCount(3)
        self.regF2.setMode(QLCDNumber.Hex)
        self.regF2.setProperty("intValue", 255)
        self.reg10 = QLCDNumber(self.memory)
        self.reg10.setObjectName(u"reg10")
        self.reg10.setGeometry(QRect(110, 50, 31, 20))
        self.reg10.setDigitCount(3)
        self.reg10.setMode(QLCDNumber.Hex)
        self.reg10.setProperty("intValue", 255)
        self.reg32 = QLCDNumber(self.memory)
        self.reg32.setObjectName(u"reg32")
        self.reg32.setGeometry(QRect(170, 90, 30, 20))
        self.reg32.setDigitCount(3)
        self.reg32.setMode(QLCDNumber.Hex)
        self.reg32.setProperty("intValue", 255)
        self.reg11 = QLCDNumber(self.memory)
        self.reg11.setObjectName(u"reg11")
        self.reg11.setGeometry(QRect(140, 50, 30, 20))
        self.reg11.setDigitCount(3)
        self.reg11.setMode(QLCDNumber.Hex)
        self.reg11.setProperty("intValue", 255)
        self.regE0 = QLCDNumber(self.memory)
        self.regE0.setObjectName(u"regE0")
        self.regE0.setGeometry(QRect(110, 310, 30, 20))
        self.regE0.setDigitCount(3)
        self.regE0.setMode(QLCDNumber.Hex)
        self.regE0.setProperty("intValue", 255)
        self.regE6 = QLCDNumber(self.memory)
        self.regE6.setObjectName(u"regE6")
        self.regE6.setGeometry(QRect(290, 310, 30, 20))
        self.regE6.setDigitCount(3)
        self.regE6.setMode(QLCDNumber.Hex)
        self.regE6.setProperty("intValue", 255)
        self.reg96 = QLCDNumber(self.memory)
        self.reg96.setObjectName(u"reg96")
        self.reg96.setGeometry(QRect(290, 210, 30, 20))
        self.reg96.setDigitCount(3)
        self.reg96.setMode(QLCDNumber.Hex)
        self.reg96.setProperty("intValue", 255)
        self.reg74 = QLCDNumber(self.memory)
        self.reg74.setObjectName(u"reg74")
        self.reg74.setGeometry(QRect(230, 170, 30, 20))
        self.reg74.setDigitCount(3)
        self.reg74.setMode(QLCDNumber.Hex)
        self.reg74.setProperty("intValue", 255)
        self.reg65 = QLCDNumber(self.memory)
        self.reg65.setObjectName(u"reg65")
        self.reg65.setGeometry(QRect(260, 150, 30, 20))
        self.reg65.setDigitCount(3)
        self.reg65.setMode(QLCDNumber.Hex)
        self.reg65.setProperty("intValue", 255)
        self.reg35 = QLCDNumber(self.memory)
        self.reg35.setObjectName(u"reg35")
        self.reg35.setGeometry(QRect(260, 90, 30, 20))
        self.reg35.setDigitCount(3)
        self.reg35.setMode(QLCDNumber.Hex)
        self.reg35.setProperty("intValue", 255)
        self.regF7 = QLCDNumber(self.memory)
        self.regF7.setObjectName(u"regF7")
        self.regF7.setGeometry(QRect(320, 330, 30, 20))
        self.regF7.setDigitCount(3)
        self.regF7.setMode(QLCDNumber.Hex)
        self.regF7.setProperty("intValue", 255)
        self.reg94 = QLCDNumber(self.memory)
        self.reg94.setObjectName(u"reg94")
        self.reg94.setGeometry(QRect(230, 210, 30, 20))
        self.reg94.setDigitCount(3)
        self.reg94.setMode(QLCDNumber.Hex)
        self.reg94.setProperty("intValue", 255)
        self.reg34 = QLCDNumber(self.memory)
        self.reg34.setObjectName(u"reg34")
        self.reg34.setGeometry(QRect(230, 90, 30, 20))
        self.reg34.setDigitCount(3)
        self.reg34.setMode(QLCDNumber.Hex)
        self.reg34.setProperty("intValue", 255)
        self.reg27 = QLCDNumber(self.memory)
        self.reg27.setObjectName(u"reg27")
        self.reg27.setGeometry(QRect(320, 70, 30, 20))
        self.reg27.setDigitCount(3)
        self.reg27.setMode(QLCDNumber.Hex)
        self.reg27.setProperty("intValue", 255)
        self.regC5 = QLCDNumber(self.memory)
        self.regC5.setObjectName(u"regC5")
        self.regC5.setGeometry(QRect(260, 270, 30, 20))
        self.regC5.setDigitCount(3)
        self.regC5.setMode(QLCDNumber.Hex)
        self.regC5.setProperty("intValue", 255)
        self.reg37 = QLCDNumber(self.memory)
        self.reg37.setObjectName(u"reg37")
        self.reg37.setGeometry(QRect(320, 90, 30, 20))
        self.reg37.setDigitCount(3)
        self.reg37.setMode(QLCDNumber.Hex)
        self.reg37.setProperty("intValue", 255)
        self.regA5 = QLCDNumber(self.memory)
        self.regA5.setObjectName(u"regA5")
        self.regA5.setGeometry(QRect(260, 230, 30, 20))
        self.regA5.setDigitCount(3)
        self.regA5.setMode(QLCDNumber.Hex)
        self.regA5.setProperty("intValue", 255)
        self.reg76 = QLCDNumber(self.memory)
        self.reg76.setObjectName(u"reg76")
        self.reg76.setGeometry(QRect(290, 170, 30, 20))
        self.reg76.setDigitCount(3)
        self.reg76.setMode(QLCDNumber.Hex)
        self.reg76.setProperty("intValue", 255)
        self.regB4 = QLCDNumber(self.memory)
        self.regB4.setObjectName(u"regB4")
        self.regB4.setGeometry(QRect(230, 250, 30, 20))
        self.regB4.setDigitCount(3)
        self.regB4.setMode(QLCDNumber.Hex)
        self.regB4.setProperty("intValue", 255)
        self.reg36 = QLCDNumber(self.memory)
        self.reg36.setObjectName(u"reg36")
        self.reg36.setGeometry(QRect(290, 90, 30, 20))
        self.reg36.setDigitCount(3)
        self.reg36.setMode(QLCDNumber.Hex)
        self.reg36.setProperty("intValue", 255)
        self.regA6 = QLCDNumber(self.memory)
        self.regA6.setObjectName(u"regA6")
        self.regA6.setGeometry(QRect(290, 230, 30, 20))
        self.regA6.setDigitCount(3)
        self.regA6.setMode(QLCDNumber.Hex)
        self.regA6.setProperty("intValue", 255)
        self.regA7 = QLCDNumber(self.memory)
        self.regA7.setObjectName(u"regA7")
        self.regA7.setGeometry(QRect(320, 230, 30, 20))
        self.regA7.setDigitCount(3)
        self.regA7.setMode(QLCDNumber.Hex)
        self.regA7.setProperty("intValue", 255)
        self.regF6 = QLCDNumber(self.memory)
        self.regF6.setObjectName(u"regF6")
        self.regF6.setGeometry(QRect(290, 330, 30, 20))
        self.regF6.setDigitCount(3)
        self.regF6.setMode(QLCDNumber.Hex)
        self.regF6.setProperty("intValue", 255)
        self.reg15 = QLCDNumber(self.memory)
        self.reg15.setObjectName(u"reg15")
        self.reg15.setGeometry(QRect(260, 50, 30, 20))
        self.reg15.setDigitCount(3)
        self.reg15.setMode(QLCDNumber.Hex)
        self.reg15.setProperty("intValue", 255)
        self.reg57 = QLCDNumber(self.memory)
        self.reg57.setObjectName(u"reg57")
        self.reg57.setGeometry(QRect(320, 130, 30, 20))
        self.reg57.setDigitCount(3)
        self.reg57.setMode(QLCDNumber.Hex)
        self.reg57.setProperty("intValue", 255)
        self.reg14 = QLCDNumber(self.memory)
        self.reg14.setObjectName(u"reg14")
        self.reg14.setGeometry(QRect(230, 50, 30, 20))
        self.reg14.setDigitCount(3)
        self.reg14.setMode(QLCDNumber.Hex)
        self.reg14.setProperty("intValue", 255)
        self.reg06 = QLCDNumber(self.memory)
        self.reg06.setObjectName(u"reg06")
        self.reg06.setGeometry(QRect(290, 30, 30, 20))
        self.reg06.setDigitCount(3)
        self.reg06.setMode(QLCDNumber.Hex)
        self.reg06.setProperty("intValue", 255)
        self.reg05 = QLCDNumber(self.memory)
        self.reg05.setObjectName(u"reg05")
        self.reg05.setGeometry(QRect(260, 30, 30, 20))
        self.reg05.setDigitCount(3)
        self.reg05.setMode(QLCDNumber.Hex)
        self.reg05.setProperty("intValue", 255)
        self.reg45 = QLCDNumber(self.memory)
        self.reg45.setObjectName(u"reg45")
        self.reg45.setGeometry(QRect(260, 110, 30, 20))
        self.reg45.setDigitCount(3)
        self.reg45.setMode(QLCDNumber.Hex)
        self.reg45.setProperty("intValue", 255)
        self.reg77 = QLCDNumber(self.memory)
        self.reg77.setObjectName(u"reg77")
        self.reg77.setGeometry(QRect(320, 170, 30, 20))
        self.reg77.setDigitCount(3)
        self.reg77.setMode(QLCDNumber.Hex)
        self.reg77.setProperty("intValue", 255)
        self.regE4 = QLCDNumber(self.memory)
        self.regE4.setObjectName(u"regE4")
        self.regE4.setGeometry(QRect(230, 310, 30, 20))
        self.regE4.setDigitCount(3)
        self.regE4.setMode(QLCDNumber.Hex)
        self.regE4.setProperty("intValue", 255)
        self.regD7 = QLCDNumber(self.memory)
        self.regD7.setObjectName(u"regD7")
        self.regD7.setGeometry(QRect(320, 290, 30, 20))
        self.regD7.setDigitCount(3)
        self.regD7.setMode(QLCDNumber.Hex)
        self.regD7.setProperty("intValue", 255)
        self.reg04 = QLCDNumber(self.memory)
        self.reg04.setObjectName(u"reg04")
        self.reg04.setGeometry(QRect(230, 30, 30, 20))
        self.reg04.setDigitCount(3)
        self.reg04.setMode(QLCDNumber.Hex)
        self.reg04.setProperty("intValue", 255)
        self.regB7 = QLCDNumber(self.memory)
        self.regB7.setObjectName(u"regB7")
        self.regB7.setGeometry(QRect(320, 250, 30, 20))
        self.regB7.setDigitCount(3)
        self.regB7.setMode(QLCDNumber.Hex)
        self.regB7.setProperty("intValue", 255)
        self.regD5 = QLCDNumber(self.memory)
        self.regD5.setObjectName(u"regD5")
        self.regD5.setGeometry(QRect(260, 290, 30, 20))
        self.regD5.setDigitCount(3)
        self.regD5.setMode(QLCDNumber.Hex)
        self.regD5.setProperty("intValue", 255)
        self.regE5 = QLCDNumber(self.memory)
        self.regE5.setObjectName(u"regE5")
        self.regE5.setGeometry(QRect(260, 310, 30, 20))
        self.regE5.setDigitCount(3)
        self.regE5.setMode(QLCDNumber.Hex)
        self.regE5.setProperty("intValue", 255)
        self.regB6 = QLCDNumber(self.memory)
        self.regB6.setObjectName(u"regB6")
        self.regB6.setGeometry(QRect(290, 250, 30, 20))
        self.regB6.setDigitCount(3)
        self.regB6.setMode(QLCDNumber.Hex)
        self.regB6.setProperty("intValue", 255)
        self.regF5 = QLCDNumber(self.memory)
        self.regF5.setObjectName(u"regF5")
        self.regF5.setGeometry(QRect(260, 330, 30, 20))
        self.regF5.setDigitCount(3)
        self.regF5.setMode(QLCDNumber.Hex)
        self.regF5.setProperty("intValue", 255)
        self.reg55 = QLCDNumber(self.memory)
        self.reg55.setObjectName(u"reg55")
        self.reg55.setGeometry(QRect(260, 130, 30, 20))
        self.reg55.setDigitCount(3)
        self.reg55.setMode(QLCDNumber.Hex)
        self.reg55.setProperty("intValue", 255)
        self.regC4 = QLCDNumber(self.memory)
        self.regC4.setObjectName(u"regC4")
        self.regC4.setGeometry(QRect(230, 270, 30, 20))
        self.regC4.setDigitCount(3)
        self.regC4.setMode(QLCDNumber.Hex)
        self.regC4.setProperty("intValue", 255)
        self.reg86 = QLCDNumber(self.memory)
        self.reg86.setObjectName(u"reg86")
        self.reg86.setGeometry(QRect(290, 190, 30, 20))
        self.reg86.setDigitCount(3)
        self.reg86.setMode(QLCDNumber.Hex)
        self.reg86.setProperty("intValue", 255)
        self.regF4 = QLCDNumber(self.memory)
        self.regF4.setObjectName(u"regF4")
        self.regF4.setGeometry(QRect(230, 330, 30, 20))
        self.regF4.setDigitCount(3)
        self.regF4.setMode(QLCDNumber.Hex)
        self.regF4.setProperty("intValue", 255)
        self.reg17 = QLCDNumber(self.memory)
        self.reg17.setObjectName(u"reg17")
        self.reg17.setGeometry(QRect(320, 50, 30, 20))
        self.reg17.setDigitCount(3)
        self.reg17.setMode(QLCDNumber.Hex)
        self.reg17.setProperty("intValue", 255)
        self.regE7 = QLCDNumber(self.memory)
        self.regE7.setObjectName(u"regE7")
        self.regE7.setGeometry(QRect(320, 310, 30, 20))
        self.regE7.setDigitCount(3)
        self.regE7.setMode(QLCDNumber.Hex)
        self.regE7.setProperty("intValue", 255)
        self.reg66 = QLCDNumber(self.memory)
        self.reg66.setObjectName(u"reg66")
        self.reg66.setGeometry(QRect(290, 150, 30, 20))
        self.reg66.setDigitCount(3)
        self.reg66.setMode(QLCDNumber.Hex)
        self.reg66.setProperty("intValue", 255)
        self.regC7 = QLCDNumber(self.memory)
        self.regC7.setObjectName(u"regC7")
        self.regC7.setGeometry(QRect(320, 270, 30, 20))
        self.regC7.setDigitCount(3)
        self.regC7.setMode(QLCDNumber.Hex)
        self.regC7.setProperty("intValue", 255)
        self.reg26 = QLCDNumber(self.memory)
        self.reg26.setObjectName(u"reg26")
        self.reg26.setGeometry(QRect(290, 70, 30, 20))
        self.reg26.setDigitCount(3)
        self.reg26.setMode(QLCDNumber.Hex)
        self.reg26.setProperty("intValue", 255)
        self.reg47 = QLCDNumber(self.memory)
        self.reg47.setObjectName(u"reg47")
        self.reg47.setGeometry(QRect(320, 110, 30, 20))
        self.reg47.setDigitCount(3)
        self.reg47.setMode(QLCDNumber.Hex)
        self.reg47.setProperty("intValue", 255)
        self.reg67 = QLCDNumber(self.memory)
        self.reg67.setObjectName(u"reg67")
        self.reg67.setGeometry(QRect(320, 150, 30, 20))
        self.reg67.setDigitCount(3)
        self.reg67.setMode(QLCDNumber.Hex)
        self.reg67.setProperty("intValue", 255)
        self.reg24 = QLCDNumber(self.memory)
        self.reg24.setObjectName(u"reg24")
        self.reg24.setGeometry(QRect(230, 70, 30, 20))
        self.reg24.setDigitCount(3)
        self.reg24.setMode(QLCDNumber.Hex)
        self.reg24.setProperty("intValue", 255)
        self.regB5 = QLCDNumber(self.memory)
        self.regB5.setObjectName(u"regB5")
        self.regB5.setGeometry(QRect(260, 250, 30, 20))
        self.regB5.setDigitCount(3)
        self.regB5.setMode(QLCDNumber.Hex)
        self.regB5.setProperty("intValue", 255)
        self.regC6 = QLCDNumber(self.memory)
        self.regC6.setObjectName(u"regC6")
        self.regC6.setGeometry(QRect(290, 270, 30, 20))
        self.regC6.setDigitCount(3)
        self.regC6.setMode(QLCDNumber.Hex)
        self.regC6.setProperty("intValue", 255)
        self.reg25 = QLCDNumber(self.memory)
        self.reg25.setObjectName(u"reg25")
        self.reg25.setGeometry(QRect(260, 70, 30, 20))
        self.reg25.setDigitCount(3)
        self.reg25.setMode(QLCDNumber.Hex)
        self.reg25.setProperty("intValue", 255)
        self.reg87 = QLCDNumber(self.memory)
        self.reg87.setObjectName(u"reg87")
        self.reg87.setGeometry(QRect(320, 190, 30, 20))
        self.reg87.setDigitCount(3)
        self.reg87.setMode(QLCDNumber.Hex)
        self.reg87.setProperty("intValue", 255)
        self.reg16 = QLCDNumber(self.memory)
        self.reg16.setObjectName(u"reg16")
        self.reg16.setGeometry(QRect(290, 50, 30, 20))
        self.reg16.setDigitCount(3)
        self.reg16.setMode(QLCDNumber.Hex)
        self.reg16.setProperty("intValue", 255)
        self.reg97 = QLCDNumber(self.memory)
        self.reg97.setObjectName(u"reg97")
        self.reg97.setGeometry(QRect(320, 210, 30, 20))
        self.reg97.setDigitCount(3)
        self.reg97.setMode(QLCDNumber.Hex)
        self.reg97.setProperty("intValue", 255)
        self.reg46 = QLCDNumber(self.memory)
        self.reg46.setObjectName(u"reg46")
        self.reg46.setGeometry(QRect(290, 110, 30, 20))
        self.reg46.setDigitCount(3)
        self.reg46.setMode(QLCDNumber.Hex)
        self.reg46.setProperty("intValue", 255)
        self.reg44 = QLCDNumber(self.memory)
        self.reg44.setObjectName(u"reg44")
        self.reg44.setGeometry(QRect(230, 110, 30, 20))
        self.reg44.setDigitCount(3)
        self.reg44.setMode(QLCDNumber.Hex)
        self.reg44.setProperty("intValue", 255)
        self.reg56 = QLCDNumber(self.memory)
        self.reg56.setObjectName(u"reg56")
        self.reg56.setGeometry(QRect(290, 130, 30, 20))
        self.reg56.setDigitCount(3)
        self.reg56.setMode(QLCDNumber.Hex)
        self.reg56.setProperty("intValue", 255)
        self.reg84 = QLCDNumber(self.memory)
        self.reg84.setObjectName(u"reg84")
        self.reg84.setGeometry(QRect(230, 190, 30, 20))
        self.reg84.setDigitCount(3)
        self.reg84.setMode(QLCDNumber.Hex)
        self.reg84.setProperty("intValue", 255)
        self.reg75 = QLCDNumber(self.memory)
        self.reg75.setObjectName(u"reg75")
        self.reg75.setGeometry(QRect(260, 170, 30, 20))
        self.reg75.setDigitCount(3)
        self.reg75.setMode(QLCDNumber.Hex)
        self.reg75.setProperty("intValue", 255)
        self.regD6 = QLCDNumber(self.memory)
        self.regD6.setObjectName(u"regD6")
        self.regD6.setGeometry(QRect(290, 290, 30, 20))
        self.regD6.setDigitCount(3)
        self.regD6.setMode(QLCDNumber.Hex)
        self.regD6.setProperty("intValue", 255)
        self.regD4 = QLCDNumber(self.memory)
        self.regD4.setObjectName(u"regD4")
        self.regD4.setGeometry(QRect(230, 290, 30, 20))
        self.regD4.setDigitCount(3)
        self.regD4.setMode(QLCDNumber.Hex)
        self.regD4.setProperty("intValue", 255)
        self.regA4 = QLCDNumber(self.memory)
        self.regA4.setObjectName(u"regA4")
        self.regA4.setGeometry(QRect(230, 230, 30, 20))
        self.regA4.setDigitCount(3)
        self.regA4.setMode(QLCDNumber.Hex)
        self.regA4.setProperty("intValue", 255)
        self.reg64 = QLCDNumber(self.memory)
        self.reg64.setObjectName(u"reg64")
        self.reg64.setGeometry(QRect(230, 150, 30, 20))
        self.reg64.setDigitCount(3)
        self.reg64.setMode(QLCDNumber.Hex)
        self.reg64.setProperty("intValue", 255)
        self.reg54 = QLCDNumber(self.memory)
        self.reg54.setObjectName(u"reg54")
        self.reg54.setGeometry(QRect(230, 130, 30, 20))
        self.reg54.setDigitCount(3)
        self.reg54.setMode(QLCDNumber.Hex)
        self.reg54.setProperty("intValue", 255)
        self.reg85 = QLCDNumber(self.memory)
        self.reg85.setObjectName(u"reg85")
        self.reg85.setGeometry(QRect(260, 190, 30, 20))
        self.reg85.setDigitCount(3)
        self.reg85.setMode(QLCDNumber.Hex)
        self.reg85.setProperty("intValue", 255)
        self.reg07 = QLCDNumber(self.memory)
        self.reg07.setObjectName(u"reg07")
        self.reg07.setGeometry(QRect(320, 30, 30, 20))
        self.reg07.setDigitCount(3)
        self.reg07.setMode(QLCDNumber.Hex)
        self.reg07.setProperty("intValue", 255)
        self.reg95 = QLCDNumber(self.memory)
        self.reg95.setObjectName(u"reg95")
        self.reg95.setGeometry(QRect(260, 210, 30, 20))
        self.reg95.setDigitCount(3)
        self.reg95.setMode(QLCDNumber.Hex)
        self.reg95.setProperty("intValue", 255)
        self.reg1B = QLCDNumber(self.memory)
        self.reg1B.setObjectName(u"reg1B")
        self.reg1B.setGeometry(QRect(440, 50, 30, 20))
        self.reg1B.setDigitCount(3)
        self.reg1B.setMode(QLCDNumber.Hex)
        self.reg1B.setProperty("intValue", 255)
        self.regF9 = QLCDNumber(self.memory)
        self.regF9.setObjectName(u"regF9")
        self.regF9.setGeometry(QRect(380, 330, 30, 20))
        self.regF9.setDigitCount(3)
        self.regF9.setMode(QLCDNumber.Hex)
        self.regF9.setProperty("intValue", 255)
        self.reg8B = QLCDNumber(self.memory)
        self.reg8B.setObjectName(u"reg8B")
        self.reg8B.setGeometry(QRect(440, 190, 30, 20))
        self.reg8B.setDigitCount(3)
        self.reg8B.setMode(QLCDNumber.Hex)
        self.reg8B.setProperty("intValue", 255)
        self.regB8 = QLCDNumber(self.memory)
        self.regB8.setObjectName(u"regB8")
        self.regB8.setGeometry(QRect(350, 250, 30, 20))
        self.regB8.setDigitCount(3)
        self.regB8.setMode(QLCDNumber.Hex)
        self.regB8.setProperty("intValue", 255)
        self.reg4A = QLCDNumber(self.memory)
        self.reg4A.setObjectName(u"reg4A")
        self.reg4A.setGeometry(QRect(410, 110, 30, 20))
        self.reg4A.setDigitCount(3)
        self.reg4A.setMode(QLCDNumber.Hex)
        self.reg4A.setProperty("intValue", 255)
        self.reg6B = QLCDNumber(self.memory)
        self.reg6B.setObjectName(u"reg6B")
        self.reg6B.setGeometry(QRect(440, 150, 30, 20))
        self.reg6B.setDigitCount(3)
        self.reg6B.setMode(QLCDNumber.Hex)
        self.reg6B.setProperty("intValue", 255)
        self.regDB = QLCDNumber(self.memory)
        self.regDB.setObjectName(u"regDB")
        self.regDB.setGeometry(QRect(440, 290, 30, 20))
        self.regDB.setDigitCount(3)
        self.regDB.setMode(QLCDNumber.Hex)
        self.regDB.setProperty("intValue", 255)
        self.reg18 = QLCDNumber(self.memory)
        self.reg18.setObjectName(u"reg18")
        self.reg18.setGeometry(QRect(350, 50, 30, 20))
        self.reg18.setDigitCount(3)
        self.reg18.setMode(QLCDNumber.Hex)
        self.reg18.setProperty("intValue", 255)
        self.reg5A = QLCDNumber(self.memory)
        self.reg5A.setObjectName(u"reg5A")
        self.reg5A.setGeometry(QRect(410, 130, 30, 20))
        self.reg5A.setDigitCount(3)
        self.reg5A.setMode(QLCDNumber.Hex)
        self.reg5A.setProperty("intValue", 255)
        self.reg78 = QLCDNumber(self.memory)
        self.reg78.setObjectName(u"reg78")
        self.reg78.setGeometry(QRect(350, 170, 30, 20))
        self.reg78.setDigitCount(3)
        self.reg78.setMode(QLCDNumber.Hex)
        self.reg78.setProperty("intValue", 255)
        self.regBA = QLCDNumber(self.memory)
        self.regBA.setObjectName(u"regBA")
        self.regBA.setGeometry(QRect(410, 250, 30, 20))
        self.regBA.setDigitCount(3)
        self.regBA.setMode(QLCDNumber.Hex)
        self.regBA.setProperty("intValue", 255)
        self.reg59 = QLCDNumber(self.memory)
        self.reg59.setObjectName(u"reg59")
        self.reg59.setGeometry(QRect(380, 130, 30, 20))
        self.reg59.setDigitCount(3)
        self.reg59.setMode(QLCDNumber.Hex)
        self.reg59.setProperty("intValue", 255)
        self.reg98 = QLCDNumber(self.memory)
        self.reg98.setObjectName(u"reg98")
        self.reg98.setGeometry(QRect(350, 210, 30, 20))
        self.reg98.setDigitCount(3)
        self.reg98.setMode(QLCDNumber.Hex)
        self.reg98.setProperty("intValue", 255)
        self.reg99 = QLCDNumber(self.memory)
        self.reg99.setObjectName(u"reg99")
        self.reg99.setGeometry(QRect(380, 210, 30, 20))
        self.reg99.setDigitCount(3)
        self.reg99.setMode(QLCDNumber.Hex)
        self.reg99.setProperty("intValue", 255)
        self.reg2B = QLCDNumber(self.memory)
        self.reg2B.setObjectName(u"reg2B")
        self.reg2B.setGeometry(QRect(440, 70, 30, 20))
        self.reg2B.setDigitCount(3)
        self.reg2B.setMode(QLCDNumber.Hex)
        self.reg2B.setProperty("intValue", 255)
        self.regEB = QLCDNumber(self.memory)
        self.regEB.setObjectName(u"regEB")
        self.regEB.setGeometry(QRect(440, 310, 30, 20))
        self.regEB.setDigitCount(3)
        self.regEB.setMode(QLCDNumber.Hex)
        self.regEB.setProperty("intValue", 255)
        self.reg49 = QLCDNumber(self.memory)
        self.reg49.setObjectName(u"reg49")
        self.reg49.setGeometry(QRect(380, 110, 30, 20))
        self.reg49.setDigitCount(3)
        self.reg49.setMode(QLCDNumber.Hex)
        self.reg49.setProperty("intValue", 255)
        self.reg0A = QLCDNumber(self.memory)
        self.reg0A.setObjectName(u"reg0A")
        self.reg0A.setGeometry(QRect(410, 30, 30, 20))
        self.reg0A.setDigitCount(3)
        self.reg0A.setMode(QLCDNumber.Hex)
        self.reg0A.setProperty("intValue", 255)
        self.regD9 = QLCDNumber(self.memory)
        self.regD9.setObjectName(u"regD9")
        self.regD9.setGeometry(QRect(380, 290, 30, 20))
        self.regD9.setDigitCount(3)
        self.regD9.setMode(QLCDNumber.Hex)
        self.regD9.setProperty("intValue", 255)
        self.reg7A = QLCDNumber(self.memory)
        self.reg7A.setObjectName(u"reg7A")
        self.reg7A.setGeometry(QRect(410, 170, 30, 20))
        self.reg7A.setDigitCount(3)
        self.reg7A.setMode(QLCDNumber.Hex)
        self.reg7A.setProperty("intValue", 255)
        self.regAB = QLCDNumber(self.memory)
        self.regAB.setObjectName(u"regAB")
        self.regAB.setGeometry(QRect(440, 230, 30, 20))
        self.regAB.setDigitCount(3)
        self.regAB.setMode(QLCDNumber.Hex)
        self.regAB.setProperty("intValue", 255)
        self.reg8A = QLCDNumber(self.memory)
        self.reg8A.setObjectName(u"reg8A")
        self.reg8A.setGeometry(QRect(410, 190, 30, 20))
        self.reg8A.setDigitCount(3)
        self.reg8A.setMode(QLCDNumber.Hex)
        self.reg8A.setProperty("intValue", 255)
        self.reg28 = QLCDNumber(self.memory)
        self.reg28.setObjectName(u"reg28")
        self.reg28.setGeometry(QRect(350, 70, 30, 20))
        self.reg28.setDigitCount(3)
        self.reg28.setMode(QLCDNumber.Hex)
        self.reg28.setProperty("intValue", 255)
        self.regEA = QLCDNumber(self.memory)
        self.regEA.setObjectName(u"regEA")
        self.regEA.setGeometry(QRect(410, 310, 30, 20))
        self.regEA.setDigitCount(3)
        self.regEA.setMode(QLCDNumber.Hex)
        self.regEA.setProperty("intValue", 255)
        self.regE9 = QLCDNumber(self.memory)
        self.regE9.setObjectName(u"regE9")
        self.regE9.setGeometry(QRect(380, 310, 30, 20))
        self.regE9.setDigitCount(3)
        self.regE9.setMode(QLCDNumber.Hex)
        self.regE9.setProperty("intValue", 255)
        self.reg19 = QLCDNumber(self.memory)
        self.reg19.setObjectName(u"reg19")
        self.reg19.setGeometry(QRect(380, 50, 30, 20))
        self.reg19.setDigitCount(3)
        self.reg19.setMode(QLCDNumber.Hex)
        self.reg19.setProperty("intValue", 255)
        self.reg38 = QLCDNumber(self.memory)
        self.reg38.setObjectName(u"reg38")
        self.reg38.setGeometry(QRect(350, 90, 30, 20))
        self.reg38.setDigitCount(3)
        self.reg38.setMode(QLCDNumber.Hex)
        self.reg38.setProperty("intValue", 255)
        self.reg29 = QLCDNumber(self.memory)
        self.reg29.setObjectName(u"reg29")
        self.reg29.setGeometry(QRect(380, 70, 30, 20))
        self.reg29.setDigitCount(3)
        self.reg29.setMode(QLCDNumber.Hex)
        self.reg29.setProperty("intValue", 255)
        self.regC9 = QLCDNumber(self.memory)
        self.regC9.setObjectName(u"regC9")
        self.regC9.setGeometry(QRect(380, 270, 30, 20))
        self.regC9.setDigitCount(3)
        self.regC9.setMode(QLCDNumber.Hex)
        self.regC9.setProperty("intValue", 255)
        self.reg79 = QLCDNumber(self.memory)
        self.reg79.setObjectName(u"reg79")
        self.reg79.setGeometry(QRect(380, 170, 30, 20))
        self.reg79.setDigitCount(3)
        self.reg79.setMode(QLCDNumber.Hex)
        self.reg79.setProperty("intValue", 255)
        self.reg9B = QLCDNumber(self.memory)
        self.reg9B.setObjectName(u"reg9B")
        self.reg9B.setGeometry(QRect(440, 210, 30, 20))
        self.reg9B.setDigitCount(3)
        self.reg9B.setMode(QLCDNumber.Hex)
        self.reg9B.setProperty("intValue", 255)
        self.regC8 = QLCDNumber(self.memory)
        self.regC8.setObjectName(u"regC8")
        self.regC8.setGeometry(QRect(350, 270, 30, 20))
        self.regC8.setDigitCount(3)
        self.regC8.setMode(QLCDNumber.Hex)
        self.regC8.setProperty("intValue", 255)
        self.regA9 = QLCDNumber(self.memory)
        self.regA9.setObjectName(u"regA9")
        self.regA9.setGeometry(QRect(380, 230, 30, 20))
        self.regA9.setDigitCount(3)
        self.regA9.setMode(QLCDNumber.Hex)
        self.regA9.setProperty("intValue", 255)
        self.reg09 = QLCDNumber(self.memory)
        self.reg09.setObjectName(u"reg09")
        self.reg09.setGeometry(QRect(380, 30, 30, 20))
        self.reg09.setDigitCount(3)
        self.reg09.setMode(QLCDNumber.Hex)
        self.reg09.setProperty("intValue", 255)
        self.regFB = QLCDNumber(self.memory)
        self.regFB.setObjectName(u"regFB")
        self.regFB.setGeometry(QRect(440, 330, 30, 20))
        self.regFB.setDigitCount(3)
        self.regFB.setMode(QLCDNumber.Hex)
        self.regFB.setProperty("intValue", 255)
        self.regFA = QLCDNumber(self.memory)
        self.regFA.setObjectName(u"regFA")
        self.regFA.setGeometry(QRect(410, 330, 30, 20))
        self.regFA.setDigitCount(3)
        self.regFA.setMode(QLCDNumber.Hex)
        self.regFA.setProperty("intValue", 255)
        self.regE8 = QLCDNumber(self.memory)
        self.regE8.setObjectName(u"regE8")
        self.regE8.setGeometry(QRect(350, 310, 30, 20))
        self.regE8.setDigitCount(3)
        self.regE8.setMode(QLCDNumber.Hex)
        self.regE8.setProperty("intValue", 255)
        self.reg0B = QLCDNumber(self.memory)
        self.reg0B.setObjectName(u"reg0B")
        self.reg0B.setGeometry(QRect(440, 30, 30, 20))
        self.reg0B.setDigitCount(3)
        self.reg0B.setMode(QLCDNumber.Hex)
        self.reg0B.setProperty("intValue", 255)
        self.reg58 = QLCDNumber(self.memory)
        self.reg58.setObjectName(u"reg58")
        self.reg58.setGeometry(QRect(350, 130, 30, 20))
        self.reg58.setDigitCount(3)
        self.reg58.setMode(QLCDNumber.Hex)
        self.reg58.setProperty("intValue", 255)
        self.reg89 = QLCDNumber(self.memory)
        self.reg89.setObjectName(u"reg89")
        self.reg89.setGeometry(QRect(380, 190, 30, 20))
        self.reg89.setDigitCount(3)
        self.reg89.setMode(QLCDNumber.Hex)
        self.reg89.setProperty("intValue", 255)
        self.regDA = QLCDNumber(self.memory)
        self.regDA.setObjectName(u"regDA")
        self.regDA.setGeometry(QRect(410, 290, 30, 20))
        self.regDA.setDigitCount(3)
        self.regDA.setMode(QLCDNumber.Hex)
        self.regDA.setProperty("intValue", 255)
        self.reg88 = QLCDNumber(self.memory)
        self.reg88.setObjectName(u"reg88")
        self.reg88.setGeometry(QRect(350, 190, 30, 20))
        self.reg88.setDigitCount(3)
        self.reg88.setMode(QLCDNumber.Hex)
        self.reg88.setProperty("intValue", 255)
        self.reg08 = QLCDNumber(self.memory)
        self.reg08.setObjectName(u"reg08")
        self.reg08.setGeometry(QRect(350, 30, 30, 20))
        self.reg08.setDigitCount(3)
        self.reg08.setMode(QLCDNumber.Hex)
        self.reg08.setProperty("intValue", 255)
        self.reg5B = QLCDNumber(self.memory)
        self.reg5B.setObjectName(u"reg5B")
        self.reg5B.setGeometry(QRect(440, 130, 30, 20))
        self.reg5B.setDigitCount(3)
        self.reg5B.setMode(QLCDNumber.Hex)
        self.reg5B.setProperty("intValue", 255)
        self.reg9A = QLCDNumber(self.memory)
        self.reg9A.setObjectName(u"reg9A")
        self.reg9A.setGeometry(QRect(410, 210, 30, 20))
        self.reg9A.setDigitCount(3)
        self.reg9A.setMode(QLCDNumber.Hex)
        self.reg9A.setProperty("intValue", 255)
        self.reg39 = QLCDNumber(self.memory)
        self.reg39.setObjectName(u"reg39")
        self.reg39.setGeometry(QRect(380, 90, 30, 20))
        self.reg39.setDigitCount(3)
        self.reg39.setMode(QLCDNumber.Hex)
        self.reg39.setProperty("intValue", 255)
        self.regAA = QLCDNumber(self.memory)
        self.regAA.setObjectName(u"regAA")
        self.regAA.setGeometry(QRect(410, 230, 30, 20))
        self.regAA.setDigitCount(3)
        self.regAA.setMode(QLCDNumber.Hex)
        self.regAA.setProperty("intValue", 255)
        self.regB9 = QLCDNumber(self.memory)
        self.regB9.setObjectName(u"regB9")
        self.regB9.setGeometry(QRect(380, 250, 30, 20))
        self.regB9.setDigitCount(3)
        self.regB9.setMode(QLCDNumber.Hex)
        self.regB9.setProperty("intValue", 255)
        self.regCA = QLCDNumber(self.memory)
        self.regCA.setObjectName(u"regCA")
        self.regCA.setGeometry(QRect(410, 270, 30, 20))
        self.regCA.setDigitCount(3)
        self.regCA.setMode(QLCDNumber.Hex)
        self.regCA.setProperty("intValue", 255)
        self.regA8 = QLCDNumber(self.memory)
        self.regA8.setObjectName(u"regA8")
        self.regA8.setGeometry(QRect(350, 230, 30, 20))
        self.regA8.setDigitCount(3)
        self.regA8.setMode(QLCDNumber.Hex)
        self.regA8.setProperty("intValue", 255)
        self.reg1A = QLCDNumber(self.memory)
        self.reg1A.setObjectName(u"reg1A")
        self.reg1A.setGeometry(QRect(410, 50, 30, 20))
        self.reg1A.setDigitCount(3)
        self.reg1A.setMode(QLCDNumber.Hex)
        self.reg1A.setProperty("intValue", 255)
        self.reg3A = QLCDNumber(self.memory)
        self.reg3A.setObjectName(u"reg3A")
        self.reg3A.setGeometry(QRect(410, 90, 30, 20))
        self.reg3A.setDigitCount(3)
        self.reg3A.setMode(QLCDNumber.Hex)
        self.reg3A.setProperty("intValue", 255)
        self.reg69 = QLCDNumber(self.memory)
        self.reg69.setObjectName(u"reg69")
        self.reg69.setGeometry(QRect(380, 150, 30, 20))
        self.reg69.setDigitCount(3)
        self.reg69.setMode(QLCDNumber.Hex)
        self.reg69.setProperty("intValue", 255)
        self.reg7B = QLCDNumber(self.memory)
        self.reg7B.setObjectName(u"reg7B")
        self.reg7B.setGeometry(QRect(440, 170, 30, 20))
        self.reg7B.setDigitCount(3)
        self.reg7B.setMode(QLCDNumber.Hex)
        self.reg7B.setProperty("intValue", 255)
        self.regCB = QLCDNumber(self.memory)
        self.regCB.setObjectName(u"regCB")
        self.regCB.setGeometry(QRect(440, 270, 30, 20))
        self.regCB.setDigitCount(3)
        self.regCB.setMode(QLCDNumber.Hex)
        self.regCB.setProperty("intValue", 255)
        self.reg2A = QLCDNumber(self.memory)
        self.reg2A.setObjectName(u"reg2A")
        self.reg2A.setGeometry(QRect(410, 70, 30, 20))
        self.reg2A.setDigitCount(3)
        self.reg2A.setMode(QLCDNumber.Hex)
        self.reg2A.setProperty("intValue", 255)
        self.reg4B = QLCDNumber(self.memory)
        self.reg4B.setObjectName(u"reg4B")
        self.reg4B.setGeometry(QRect(440, 110, 30, 20))
        self.reg4B.setDigitCount(3)
        self.reg4B.setMode(QLCDNumber.Hex)
        self.reg4B.setProperty("intValue", 255)
        self.reg3B = QLCDNumber(self.memory)
        self.reg3B.setObjectName(u"reg3B")
        self.reg3B.setGeometry(QRect(440, 90, 30, 20))
        self.reg3B.setDigitCount(3)
        self.reg3B.setMode(QLCDNumber.Hex)
        self.reg3B.setProperty("intValue", 255)
        self.reg6A = QLCDNumber(self.memory)
        self.reg6A.setObjectName(u"reg6A")
        self.reg6A.setGeometry(QRect(410, 150, 30, 20))
        self.reg6A.setDigitCount(3)
        self.reg6A.setMode(QLCDNumber.Hex)
        self.reg6A.setProperty("intValue", 255)
        self.regBB = QLCDNumber(self.memory)
        self.regBB.setObjectName(u"regBB")
        self.regBB.setGeometry(QRect(440, 250, 30, 20))
        self.regBB.setDigitCount(3)
        self.regBB.setMode(QLCDNumber.Hex)
        self.regBB.setProperty("intValue", 255)
        self.regD8 = QLCDNumber(self.memory)
        self.regD8.setObjectName(u"regD8")
        self.regD8.setGeometry(QRect(350, 290, 30, 20))
        self.regD8.setDigitCount(3)
        self.regD8.setMode(QLCDNumber.Hex)
        self.regD8.setProperty("intValue", 255)
        self.reg68 = QLCDNumber(self.memory)
        self.reg68.setObjectName(u"reg68")
        self.reg68.setGeometry(QRect(350, 150, 30, 20))
        self.reg68.setDigitCount(3)
        self.reg68.setMode(QLCDNumber.Hex)
        self.reg68.setProperty("intValue", 255)
        self.regF8 = QLCDNumber(self.memory)
        self.regF8.setObjectName(u"regF8")
        self.regF8.setGeometry(QRect(350, 330, 30, 20))
        self.regF8.setDigitCount(3)
        self.regF8.setMode(QLCDNumber.Hex)
        self.regF8.setProperty("intValue", 255)
        self.reg48 = QLCDNumber(self.memory)
        self.reg48.setObjectName(u"reg48")
        self.reg48.setGeometry(QRect(350, 110, 30, 20))
        self.reg48.setDigitCount(3)
        self.reg48.setMode(QLCDNumber.Hex)
        self.reg48.setProperty("intValue", 255)
        self.regBE = QLCDNumber(self.memory)
        self.regBE.setObjectName(u"regBE")
        self.regBE.setGeometry(QRect(530, 250, 30, 20))
        self.regBE.setDigitCount(3)
        self.regBE.setMode(QLCDNumber.Hex)
        self.regBE.setProperty("intValue", 255)
        self.reg2F = QLCDNumber(self.memory)
        self.reg2F.setObjectName(u"reg2F")
        self.reg2F.setGeometry(QRect(560, 70, 30, 20))
        self.reg2F.setDigitCount(3)
        self.reg2F.setMode(QLCDNumber.Hex)
        self.reg2F.setProperty("intValue", 255)
        self.reg4D = QLCDNumber(self.memory)
        self.reg4D.setObjectName(u"reg4D")
        self.reg4D.setGeometry(QRect(500, 110, 30, 20))
        self.reg4D.setDigitCount(3)
        self.reg4D.setMode(QLCDNumber.Hex)
        self.reg4D.setProperty("intValue", 255)
        self.reg9E = QLCDNumber(self.memory)
        self.reg9E.setObjectName(u"reg9E")
        self.reg9E.setGeometry(QRect(530, 210, 30, 20))
        self.reg9E.setDigitCount(3)
        self.reg9E.setMode(QLCDNumber.Hex)
        self.reg9E.setProperty("intValue", 255)
        self.reg5C = QLCDNumber(self.memory)
        self.reg5C.setObjectName(u"reg5C")
        self.reg5C.setGeometry(QRect(470, 130, 30, 20))
        self.reg5C.setDigitCount(3)
        self.reg5C.setMode(QLCDNumber.Hex)
        self.reg5C.setProperty("intValue", 255)
        self.reg7D = QLCDNumber(self.memory)
        self.reg7D.setObjectName(u"reg7D")
        self.reg7D.setGeometry(QRect(500, 170, 30, 20))
        self.reg7D.setDigitCount(3)
        self.reg7D.setMode(QLCDNumber.Hex)
        self.reg7D.setProperty("intValue", 255)
        self.regFD = QLCDNumber(self.memory)
        self.regFD.setObjectName(u"regFD")
        self.regFD.setGeometry(QRect(500, 330, 30, 20))
        self.regFD.setDigitCount(3)
        self.regFD.setMode(QLCDNumber.Hex)
        self.regFD.setProperty("intValue", 255)
        self.reg7F = QLCDNumber(self.memory)
        self.reg7F.setObjectName(u"reg7F")
        self.reg7F.setGeometry(QRect(560, 170, 30, 20))
        self.reg7F.setDigitCount(3)
        self.reg7F.setMode(QLCDNumber.Hex)
        self.reg7F.setProperty("intValue", 255)
        self.regDC = QLCDNumber(self.memory)
        self.regDC.setObjectName(u"regDC")
        self.regDC.setGeometry(QRect(470, 290, 30, 20))
        self.regDC.setDigitCount(3)
        self.regDC.setMode(QLCDNumber.Hex)
        self.regDC.setProperty("intValue", 255)
        self.regBD = QLCDNumber(self.memory)
        self.regBD.setObjectName(u"regBD")
        self.regBD.setGeometry(QRect(500, 250, 30, 20))
        self.regBD.setDigitCount(3)
        self.regBD.setMode(QLCDNumber.Hex)
        self.regBD.setProperty("intValue", 255)
        self.reg4E = QLCDNumber(self.memory)
        self.reg4E.setObjectName(u"reg4E")
        self.reg4E.setGeometry(QRect(530, 110, 30, 20))
        self.reg4E.setDigitCount(3)
        self.reg4E.setMode(QLCDNumber.Hex)
        self.reg4E.setProperty("intValue", 255)
        self.reg1C = QLCDNumber(self.memory)
        self.reg1C.setObjectName(u"reg1C")
        self.reg1C.setGeometry(QRect(470, 50, 30, 20))
        self.reg1C.setDigitCount(3)
        self.reg1C.setMode(QLCDNumber.Hex)
        self.reg1C.setProperty("intValue", 255)
        self.reg5D = QLCDNumber(self.memory)
        self.reg5D.setObjectName(u"reg5D")
        self.reg5D.setGeometry(QRect(500, 130, 30, 20))
        self.reg5D.setDigitCount(3)
        self.reg5D.setMode(QLCDNumber.Hex)
        self.reg5D.setProperty("intValue", 255)
        self.reg8C = QLCDNumber(self.memory)
        self.reg8C.setObjectName(u"reg8C")
        self.reg8C.setGeometry(QRect(470, 190, 30, 20))
        self.reg8C.setDigitCount(3)
        self.reg8C.setMode(QLCDNumber.Hex)
        self.reg8C.setProperty("intValue", 255)
        self.reg7E = QLCDNumber(self.memory)
        self.reg7E.setObjectName(u"reg7E")
        self.reg7E.setGeometry(QRect(530, 170, 30, 20))
        self.reg7E.setDigitCount(3)
        self.reg7E.setMode(QLCDNumber.Hex)
        self.reg7E.setProperty("intValue", 255)
        self.regAD = QLCDNumber(self.memory)
        self.regAD.setObjectName(u"regAD")
        self.regAD.setGeometry(QRect(500, 230, 30, 20))
        self.regAD.setDigitCount(3)
        self.regAD.setMode(QLCDNumber.Hex)
        self.regAD.setProperty("intValue", 255)
        self.reg3C = QLCDNumber(self.memory)
        self.reg3C.setObjectName(u"reg3C")
        self.reg3C.setGeometry(QRect(470, 90, 30, 20))
        self.reg3C.setDigitCount(3)
        self.reg3C.setMode(QLCDNumber.Hex)
        self.reg3C.setProperty("intValue", 255)
        self.reg3F = QLCDNumber(self.memory)
        self.reg3F.setObjectName(u"reg3F")
        self.reg3F.setGeometry(QRect(560, 90, 30, 20))
        self.reg3F.setDigitCount(3)
        self.reg3F.setMode(QLCDNumber.Hex)
        self.reg3F.setProperty("intValue", 255)
        self.regCE = QLCDNumber(self.memory)
        self.regCE.setObjectName(u"regCE")
        self.regCE.setGeometry(QRect(530, 270, 30, 20))
        self.regCE.setDigitCount(3)
        self.regCE.setMode(QLCDNumber.Hex)
        self.regCE.setProperty("intValue", 255)
        self.reg0D = QLCDNumber(self.memory)
        self.reg0D.setObjectName(u"reg0D")
        self.reg0D.setGeometry(QRect(500, 30, 30, 20))
        self.reg0D.setDigitCount(3)
        self.reg0D.setMode(QLCDNumber.Hex)
        self.reg0D.setProperty("intValue", 255)
        self.regDE = QLCDNumber(self.memory)
        self.regDE.setObjectName(u"regDE")
        self.regDE.setGeometry(QRect(530, 290, 30, 20))
        self.regDE.setDigitCount(3)
        self.regDE.setMode(QLCDNumber.Hex)
        self.regDE.setProperty("intValue", 255)
        self.reg6E = QLCDNumber(self.memory)
        self.reg6E.setObjectName(u"reg6E")
        self.reg6E.setGeometry(QRect(530, 150, 30, 20))
        self.reg6E.setDigitCount(3)
        self.reg6E.setMode(QLCDNumber.Hex)
        self.reg6E.setProperty("intValue", 255)
        self.reg3D = QLCDNumber(self.memory)
        self.reg3D.setObjectName(u"reg3D")
        self.reg3D.setGeometry(QRect(500, 90, 30, 20))
        self.reg3D.setDigitCount(3)
        self.reg3D.setMode(QLCDNumber.Hex)
        self.reg3D.setProperty("intValue", 255)
        self.regEC = QLCDNumber(self.memory)
        self.regEC.setObjectName(u"regEC")
        self.regEC.setGeometry(QRect(470, 310, 30, 20))
        self.regEC.setDigitCount(3)
        self.regEC.setMode(QLCDNumber.Hex)
        self.regEC.setProperty("intValue", 255)
        self.regED = QLCDNumber(self.memory)
        self.regED.setObjectName(u"regED")
        self.regED.setGeometry(QRect(500, 310, 30, 20))
        self.regED.setDigitCount(3)
        self.regED.setMode(QLCDNumber.Hex)
        self.regED.setProperty("intValue", 255)
        self.regBC = QLCDNumber(self.memory)
        self.regBC.setObjectName(u"regBC")
        self.regBC.setGeometry(QRect(470, 250, 30, 20))
        self.regBC.setDigitCount(3)
        self.regBC.setMode(QLCDNumber.Hex)
        self.regBC.setProperty("intValue", 255)
        self.reg2C = QLCDNumber(self.memory)
        self.reg2C.setObjectName(u"reg2C")
        self.reg2C.setGeometry(QRect(470, 70, 30, 20))
        self.reg2C.setDigitCount(3)
        self.reg2C.setMode(QLCDNumber.Hex)
        self.reg2C.setProperty("intValue", 255)
        self.reg6C = QLCDNumber(self.memory)
        self.reg6C.setObjectName(u"reg6C")
        self.reg6C.setGeometry(QRect(470, 150, 30, 20))
        self.reg6C.setDigitCount(3)
        self.reg6C.setMode(QLCDNumber.Hex)
        self.reg6C.setProperty("intValue", 255)
        self.reg9D = QLCDNumber(self.memory)
        self.reg9D.setObjectName(u"reg9D")
        self.reg9D.setGeometry(QRect(500, 210, 30, 20))
        self.reg9D.setDigitCount(3)
        self.reg9D.setMode(QLCDNumber.Hex)
        self.reg9D.setProperty("intValue", 255)
        self.reg4C = QLCDNumber(self.memory)
        self.reg4C.setObjectName(u"reg4C")
        self.reg4C.setGeometry(QRect(470, 110, 30, 20))
        self.reg4C.setDigitCount(3)
        self.reg4C.setMode(QLCDNumber.Hex)
        self.reg4C.setProperty("intValue", 255)
        self.reg1F = QLCDNumber(self.memory)
        self.reg1F.setObjectName(u"reg1F")
        self.reg1F.setGeometry(QRect(560, 50, 30, 20))
        self.reg1F.setDigitCount(3)
        self.reg1F.setMode(QLCDNumber.Hex)
        self.reg1F.setProperty("intValue", 255)
        self.reg1E = QLCDNumber(self.memory)
        self.reg1E.setObjectName(u"reg1E")
        self.reg1E.setGeometry(QRect(530, 50, 30, 20))
        self.reg1E.setDigitCount(3)
        self.reg1E.setMode(QLCDNumber.Hex)
        self.reg1E.setProperty("intValue", 255)
        self.reg2D = QLCDNumber(self.memory)
        self.reg2D.setObjectName(u"reg2D")
        self.reg2D.setGeometry(QRect(500, 70, 30, 20))
        self.reg2D.setDigitCount(3)
        self.reg2D.setMode(QLCDNumber.Hex)
        self.reg2D.setProperty("intValue", 255)
        self.regAE = QLCDNumber(self.memory)
        self.regAE.setObjectName(u"regAE")
        self.regAE.setGeometry(QRect(530, 230, 30, 20))
        self.regAE.setDigitCount(3)
        self.regAE.setMode(QLCDNumber.Hex)
        self.regAE.setProperty("intValue", 255)
        self.regDF = QLCDNumber(self.memory)
        self.regDF.setObjectName(u"regDF")
        self.regDF.setGeometry(QRect(560, 290, 30, 20))
        self.regDF.setDigitCount(3)
        self.regDF.setMode(QLCDNumber.Hex)
        self.regDF.setProperty("intValue", 255)
        self.regBF = QLCDNumber(self.memory)
        self.regBF.setObjectName(u"regBF")
        self.regBF.setGeometry(QRect(560, 250, 30, 20))
        self.regBF.setDigitCount(3)
        self.regBF.setMode(QLCDNumber.Hex)
        self.regBF.setProperty("intValue", 255)
        self.reg7C = QLCDNumber(self.memory)
        self.reg7C.setObjectName(u"reg7C")
        self.reg7C.setGeometry(QRect(470, 170, 30, 20))
        self.reg7C.setDigitCount(3)
        self.reg7C.setMode(QLCDNumber.Hex)
        self.reg7C.setProperty("intValue", 255)
        self.reg6F = QLCDNumber(self.memory)
        self.reg6F.setObjectName(u"reg6F")
        self.reg6F.setGeometry(QRect(560, 150, 30, 20))
        self.reg6F.setDigitCount(3)
        self.reg6F.setMode(QLCDNumber.Hex)
        self.reg6F.setProperty("intValue", 255)
        self.reg2E = QLCDNumber(self.memory)
        self.reg2E.setObjectName(u"reg2E")
        self.reg2E.setGeometry(QRect(530, 70, 30, 20))
        self.reg2E.setDigitCount(3)
        self.reg2E.setMode(QLCDNumber.Hex)
        self.reg2E.setProperty("intValue", 255)
        self.regAF = QLCDNumber(self.memory)
        self.regAF.setObjectName(u"regAF")
        self.regAF.setGeometry(QRect(560, 230, 30, 20))
        self.regAF.setDigitCount(3)
        self.regAF.setMode(QLCDNumber.Hex)
        self.regAF.setProperty("intValue", 255)
        self.reg9C = QLCDNumber(self.memory)
        self.reg9C.setObjectName(u"reg9C")
        self.reg9C.setGeometry(QRect(470, 210, 30, 20))
        self.reg9C.setDigitCount(3)
        self.reg9C.setMode(QLCDNumber.Hex)
        self.reg9C.setProperty("intValue", 255)
        self.regEE = QLCDNumber(self.memory)
        self.regEE.setObjectName(u"regEE")
        self.regEE.setGeometry(QRect(530, 310, 30, 20))
        self.regEE.setDigitCount(3)
        self.regEE.setMode(QLCDNumber.Hex)
        self.regEE.setProperty("intValue", 255)
        self.reg1D = QLCDNumber(self.memory)
        self.reg1D.setObjectName(u"reg1D")
        self.reg1D.setGeometry(QRect(500, 50, 30, 20))
        self.reg1D.setDigitCount(3)
        self.reg1D.setMode(QLCDNumber.Hex)
        self.reg1D.setProperty("intValue", 255)
        self.reg4F = QLCDNumber(self.memory)
        self.reg4F.setObjectName(u"reg4F")
        self.reg4F.setGeometry(QRect(560, 110, 30, 20))
        self.reg4F.setDigitCount(3)
        self.reg4F.setMode(QLCDNumber.Hex)
        self.reg4F.setProperty("intValue", 255)
        self.reg8F = QLCDNumber(self.memory)
        self.reg8F.setObjectName(u"reg8F")
        self.reg8F.setGeometry(QRect(560, 190, 30, 20))
        self.reg8F.setDigitCount(3)
        self.reg8F.setMode(QLCDNumber.Hex)
        self.reg8F.setProperty("intValue", 255)
        self.regCC = QLCDNumber(self.memory)
        self.regCC.setObjectName(u"regCC")
        self.regCC.setGeometry(QRect(470, 270, 30, 20))
        self.regCC.setDigitCount(3)
        self.regCC.setMode(QLCDNumber.Hex)
        self.regCC.setProperty("intValue", 255)
        self.regCF = QLCDNumber(self.memory)
        self.regCF.setObjectName(u"regCF")
        self.regCF.setGeometry(QRect(560, 270, 30, 20))
        self.regCF.setDigitCount(3)
        self.regCF.setMode(QLCDNumber.Hex)
        self.regCF.setProperty("intValue", 255)
        self.reg0E = QLCDNumber(self.memory)
        self.reg0E.setObjectName(u"reg0E")
        self.reg0E.setGeometry(QRect(530, 30, 30, 20))
        self.reg0E.setDigitCount(3)
        self.reg0E.setMode(QLCDNumber.Hex)
        self.reg0E.setProperty("intValue", 255)
        self.reg5F = QLCDNumber(self.memory)
        self.reg5F.setObjectName(u"reg5F")
        self.reg5F.setGeometry(QRect(560, 130, 30, 20))
        self.reg5F.setDigitCount(3)
        self.reg5F.setMode(QLCDNumber.Hex)
        self.reg5F.setProperty("intValue", 255)
        self.reg8E = QLCDNumber(self.memory)
        self.reg8E.setObjectName(u"reg8E")
        self.reg8E.setGeometry(QRect(530, 190, 30, 20))
        self.reg8E.setDigitCount(3)
        self.reg8E.setMode(QLCDNumber.Hex)
        self.reg8E.setProperty("intValue", 255)
        self.regDD = QLCDNumber(self.memory)
        self.regDD.setObjectName(u"regDD")
        self.regDD.setGeometry(QRect(500, 290, 30, 20))
        self.regDD.setDigitCount(3)
        self.regDD.setMode(QLCDNumber.Hex)
        self.regDD.setProperty("intValue", 255)
        self.reg3E = QLCDNumber(self.memory)
        self.reg3E.setObjectName(u"reg3E")
        self.reg3E.setGeometry(QRect(530, 90, 30, 20))
        self.reg3E.setDigitCount(3)
        self.reg3E.setMode(QLCDNumber.Hex)
        self.reg3E.setProperty("intValue", 255)
        self.reg6D = QLCDNumber(self.memory)
        self.reg6D.setObjectName(u"reg6D")
        self.reg6D.setGeometry(QRect(500, 150, 30, 20))
        self.reg6D.setDigitCount(3)
        self.reg6D.setMode(QLCDNumber.Hex)
        self.reg6D.setProperty("intValue", 255)
        self.reg0F = QLCDNumber(self.memory)
        self.reg0F.setObjectName(u"reg0F")
        self.reg0F.setGeometry(QRect(560, 30, 30, 20))
        self.reg0F.setDigitCount(3)
        self.reg0F.setMode(QLCDNumber.Hex)
        self.reg0F.setProperty("intValue", 255)
        self.regEF = QLCDNumber(self.memory)
        self.regEF.setObjectName(u"regEF")
        self.regEF.setGeometry(QRect(560, 310, 30, 20))
        self.regEF.setDigitCount(3)
        self.regEF.setMode(QLCDNumber.Hex)
        self.regEF.setProperty("intValue", 255)
        self.reg9F = QLCDNumber(self.memory)
        self.reg9F.setObjectName(u"reg9F")
        self.reg9F.setGeometry(QRect(560, 210, 30, 20))
        self.reg9F.setDigitCount(3)
        self.reg9F.setMode(QLCDNumber.Hex)
        self.reg9F.setProperty("intValue", 255)
        self.regFF = QLCDNumber(self.memory)
        self.regFF.setObjectName(u"regFF")
        self.regFF.setGeometry(QRect(560, 330, 30, 20))
        self.regFF.setDigitCount(3)
        self.regFF.setMode(QLCDNumber.Hex)
        self.regFF.setProperty("intValue", 255)
        self.regAC = QLCDNumber(self.memory)
        self.regAC.setObjectName(u"regAC")
        self.regAC.setGeometry(QRect(470, 230, 30, 20))
        self.regAC.setDigitCount(3)
        self.regAC.setMode(QLCDNumber.Hex)
        self.regAC.setProperty("intValue", 255)
        self.reg5E = QLCDNumber(self.memory)
        self.reg5E.setObjectName(u"reg5E")
        self.reg5E.setGeometry(QRect(530, 130, 30, 20))
        self.reg5E.setDigitCount(3)
        self.reg5E.setMode(QLCDNumber.Hex)
        self.reg5E.setProperty("intValue", 255)
        self.regFC = QLCDNumber(self.memory)
        self.regFC.setObjectName(u"regFC")
        self.regFC.setGeometry(QRect(470, 330, 30, 20))
        self.regFC.setDigitCount(3)
        self.regFC.setMode(QLCDNumber.Hex)
        self.regFC.setProperty("intValue", 255)
        self.regFE = QLCDNumber(self.memory)
        self.regFE.setObjectName(u"regFE")
        self.regFE.setGeometry(QRect(530, 330, 30, 20))
        self.regFE.setDigitCount(3)
        self.regFE.setMode(QLCDNumber.Hex)
        self.regFE.setProperty("intValue", 255)
        self.reg0C = QLCDNumber(self.memory)
        self.reg0C.setObjectName(u"reg0C")
        self.reg0C.setGeometry(QRect(470, 30, 30, 20))
        self.reg0C.setDigitCount(3)
        self.reg0C.setMode(QLCDNumber.Hex)
        self.reg0C.setProperty("intValue", 255)
        self.reg8D = QLCDNumber(self.memory)
        self.reg8D.setObjectName(u"reg8D")
        self.reg8D.setGeometry(QRect(500, 190, 30, 20))
        self.reg8D.setDigitCount(3)
        self.reg8D.setMode(QLCDNumber.Hex)
        self.reg8D.setProperty("intValue", 255)
        self.regCD = QLCDNumber(self.memory)
        self.regCD.setObjectName(u"regCD")
        self.regCD.setGeometry(QRect(500, 270, 30, 20))
        self.regCD.setDigitCount(3)
        self.regCD.setMode(QLCDNumber.Hex)
        self.regCD.setProperty("intValue", 255)
        self.page = QLabel(self.memory)
        self.page.setObjectName(u"page")
        self.page.setGeometry(QRect(20, 170, 41, 31))
        font2 = QFont()
        font2.setPointSize(22)
        self.page.setFont(font2)
        self.page.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page.setIndent(6)
        self.data = QLabel(self.memory)
        self.data.setObjectName(u"data")
        self.data.setGeometry(QRect(620, 170, 41, 31))
        self.data.setFont(font2)
        self.data.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.data.setIndent(6)
        self.page_col_1 = QLabel(self.memory)
        self.page_col_1.setObjectName(u"page_col_1")
        self.page_col_1.setGeometry(QRect(140, 10, 31, 20))
        font3 = QFont()
        font3.setPointSize(14)
        self.page_col_1.setFont(font3)
        self.page_col_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_1.setIndent(5)
        self.page_col_2 = QLabel(self.memory)
        self.page_col_2.setObjectName(u"page_col_2")
        self.page_col_2.setGeometry(QRect(170, 10, 31, 20))
        self.page_col_2.setFont(font3)
        self.page_col_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_2.setIndent(5)
        self.page_col_3 = QLabel(self.memory)
        self.page_col_3.setObjectName(u"page_col_3")
        self.page_col_3.setGeometry(QRect(200, 10, 31, 20))
        self.page_col_3.setFont(font3)
        self.page_col_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_3.setIndent(5)
        self.page_col_4 = QLabel(self.memory)
        self.page_col_4.setObjectName(u"page_col_4")
        self.page_col_4.setGeometry(QRect(230, 10, 31, 20))
        self.page_col_4.setFont(font3)
        self.page_col_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_4.setIndent(5)
        self.page_col_5 = QLabel(self.memory)
        self.page_col_5.setObjectName(u"page_col_5")
        self.page_col_5.setGeometry(QRect(260, 10, 31, 20))
        self.page_col_5.setFont(font3)
        self.page_col_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_5.setIndent(5)
        self.page_col_6 = QLabel(self.memory)
        self.page_col_6.setObjectName(u"page_col_6")
        self.page_col_6.setGeometry(QRect(290, 10, 31, 20))
        self.page_col_6.setFont(font3)
        self.page_col_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_6.setIndent(5)
        self.page_col_7 = QLabel(self.memory)
        self.page_col_7.setObjectName(u"page_col_7")
        self.page_col_7.setGeometry(QRect(320, 10, 31, 20))
        self.page_col_7.setFont(font3)
        self.page_col_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_7.setIndent(5)
        self.page_col_8 = QLabel(self.memory)
        self.page_col_8.setObjectName(u"page_col_8")
        self.page_col_8.setGeometry(QRect(350, 10, 31, 20))
        self.page_col_8.setFont(font3)
        self.page_col_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_8.setIndent(5)
        self.page_col_9 = QLabel(self.memory)
        self.page_col_9.setObjectName(u"page_col_9")
        self.page_col_9.setGeometry(QRect(380, 10, 31, 20))
        self.page_col_9.setFont(font3)
        self.page_col_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_9.setIndent(5)
        self.page_col_A = QLabel(self.memory)
        self.page_col_A.setObjectName(u"page_col_A")
        self.page_col_A.setGeometry(QRect(410, 10, 31, 20))
        self.page_col_A.setFont(font3)
        self.page_col_A.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_A.setIndent(5)
        self.page_col_B = QLabel(self.memory)
        self.page_col_B.setObjectName(u"page_col_B")
        self.page_col_B.setGeometry(QRect(440, 10, 31, 20))
        self.page_col_B.setFont(font3)
        self.page_col_B.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_B.setIndent(5)
        self.page_col_C = QLabel(self.memory)
        self.page_col_C.setObjectName(u"page_col_C")
        self.page_col_C.setGeometry(QRect(470, 10, 31, 20))
        self.page_col_C.setFont(font3)
        self.page_col_C.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_C.setIndent(5)
        self.page_col_D = QLabel(self.memory)
        self.page_col_D.setObjectName(u"page_col_D")
        self.page_col_D.setGeometry(QRect(500, 10, 31, 20))
        self.page_col_D.setFont(font3)
        self.page_col_D.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_D.setIndent(5)
        self.page_col_E = QLabel(self.memory)
        self.page_col_E.setObjectName(u"page_col_E")
        self.page_col_E.setGeometry(QRect(530, 10, 31, 20))
        self.page_col_E.setFont(font3)
        self.page_col_E.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_E.setIndent(5)
        self.page_col_F = QLabel(self.memory)
        self.page_col_F.setObjectName(u"page_col_F")
        self.page_col_F.setGeometry(QRect(560, 10, 31, 20))
        self.page_col_F.setFont(font3)
        self.page_col_F.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_col_F.setIndent(5)
        self.page_row_0 = QLabel(self.memory)
        self.page_row_0.setObjectName(u"page_row_0")
        self.page_row_0.setGeometry(QRect(80, 30, 31, 20))
        self.page_row_0.setFont(font3)
        self.page_row_0.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_0.setIndent(5)
        self.page_row_1 = QLabel(self.memory)
        self.page_row_1.setObjectName(u"page_row_1")
        self.page_row_1.setGeometry(QRect(80, 50, 31, 20))
        self.page_row_1.setFont(font3)
        self.page_row_1.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_1.setIndent(5)
        self.page_row_2 = QLabel(self.memory)
        self.page_row_2.setObjectName(u"page_row_2")
        self.page_row_2.setGeometry(QRect(80, 70, 31, 20))
        self.page_row_2.setFont(font3)
        self.page_row_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_2.setIndent(5)
        self.page_row_3 = QLabel(self.memory)
        self.page_row_3.setObjectName(u"page_row_3")
        self.page_row_3.setGeometry(QRect(80, 90, 31, 20))
        self.page_row_3.setFont(font3)
        self.page_row_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_3.setIndent(5)
        self.page_row_4 = QLabel(self.memory)
        self.page_row_4.setObjectName(u"page_row_4")
        self.page_row_4.setGeometry(QRect(80, 110, 31, 20))
        self.page_row_4.setFont(font3)
        self.page_row_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_4.setIndent(5)
        self.page_row_5 = QLabel(self.memory)
        self.page_row_5.setObjectName(u"page_row_5")
        self.page_row_5.setGeometry(QRect(80, 130, 31, 20))
        self.page_row_5.setFont(font3)
        self.page_row_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_5.setIndent(5)
        self.page_row_6 = QLabel(self.memory)
        self.page_row_6.setObjectName(u"page_row_6")
        self.page_row_6.setGeometry(QRect(80, 150, 31, 20))
        self.page_row_6.setFont(font3)
        self.page_row_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_6.setIndent(5)
        self.page_row_7 = QLabel(self.memory)
        self.page_row_7.setObjectName(u"page_row_7")
        self.page_row_7.setGeometry(QRect(80, 170, 31, 20))
        self.page_row_7.setFont(font3)
        self.page_row_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_7.setIndent(5)
        self.page_row_8 = QLabel(self.memory)
        self.page_row_8.setObjectName(u"page_row_8")
        self.page_row_8.setGeometry(QRect(80, 190, 31, 20))
        self.page_row_8.setFont(font3)
        self.page_row_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_8.setIndent(5)
        self.page_row_9 = QLabel(self.memory)
        self.page_row_9.setObjectName(u"page_row_9")
        self.page_row_9.setGeometry(QRect(80, 210, 31, 20))
        self.page_row_9.setFont(font3)
        self.page_row_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_9.setIndent(5)
        self.page_row_A = QLabel(self.memory)
        self.page_row_A.setObjectName(u"page_row_A")
        self.page_row_A.setGeometry(QRect(80, 230, 31, 20))
        self.page_row_A.setFont(font3)
        self.page_row_A.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_A.setIndent(5)
        self.page_row_B = QLabel(self.memory)
        self.page_row_B.setObjectName(u"page_row_B")
        self.page_row_B.setGeometry(QRect(80, 250, 31, 20))
        self.page_row_B.setFont(font3)
        self.page_row_B.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_B.setIndent(5)
        self.page_row_C = QLabel(self.memory)
        self.page_row_C.setObjectName(u"page_row_C")
        self.page_row_C.setGeometry(QRect(80, 270, 31, 20))
        self.page_row_C.setFont(font3)
        self.page_row_C.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_C.setIndent(5)
        self.page_row_E = QLabel(self.memory)
        self.page_row_E.setObjectName(u"page_row_E")
        self.page_row_E.setGeometry(QRect(80, 310, 31, 20))
        self.page_row_E.setFont(font3)
        self.page_row_E.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_E.setIndent(5)
        self.page_row_F = QLabel(self.memory)
        self.page_row_F.setObjectName(u"page_row_F")
        self.page_row_F.setGeometry(QRect(80, 330, 31, 20))
        self.page_row_F.setFont(font3)
        self.page_row_F.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_F.setIndent(5)
        self.page_row_D = QLabel(self.memory)
        self.page_row_D.setObjectName(u"page_row_D")
        self.page_row_D.setGeometry(QRect(80, 290, 31, 20))
        self.page_row_D.setFont(font3)
        self.page_row_D.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.page_row_D.setIndent(5)
        self.frame_2 = QFrame(self.simulator)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(260, 60, 141, 81))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.accumulator_binary = QLCDNumber(self.frame_2)
        self.accumulator_binary.setObjectName(u"accumulator_binary")
        self.accumulator_binary.setGeometry(QRect(10, 40, 111, 31))
        self.accumulator_binary.setDigitCount(8)
        self.accumulator_binary.setMode(QLCDNumber.Bin)
        self.accumulator = QLCDNumber(self.frame_2)
        self.accumulator.setObjectName(u"accumulator")
        self.accumulator.setGeometry(QRect(10, 10, 51, 31))
        self.accumulator.setDigitCount(3)
        self.accumulator.setMode(QLCDNumber.Hex)
        self.accumulator.setProperty("intValue", 255)
        self.frame_3 = QFrame(self.simulator)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(50, 60, 141, 71))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.status_register = QLCDNumber(self.frame_3)
        self.status_register.setObjectName(u"status_register")
        self.status_register.setGeometry(QRect(10, 30, 121, 31))
        self.status_register.setDigitCount(8)
        self.status_register.setMode(QLCDNumber.Bin)
        self.label_2 = QLabel(self.frame_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 121, 21))
        font4 = QFont()
        font4.setFamilies([u"Noto Sans Mono"])
        font4.setPointSize(11)
        self.label_2.setFont(font4)
        self.line = QFrame(self.simulator)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(90, 330, 181, 20))
        self.line.setMidLineWidth(4)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_7 = QLabel(self.simulator)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(50, 180, 131, 20))
        self.label_7.setFont(font)
        self.label_4 = QLabel(self.simulator)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(260, 40, 101, 20))
        self.label_4.setFont(font)
        self.label_10 = QLabel(self.simulator)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(50, 730, 81, 21))
        self.label_10.setFont(font)
        self.label_11 = QLabel(self.simulator)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(50, 37, 141, 21))
        self.label_11.setFont(font)
        self.frame_4 = QFrame(self.simulator)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(450, 309, 120, 51))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.cycle_counter = QLabel(self.frame_4)
        self.cycle_counter.setObjectName(u"cycle_counter")
        self.cycle_counter.setGeometry(QRect(10, 10, 101, 31))
        self.cycle_counter.setFont(font2)
        self.label_12 = QLabel(self.simulator)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(450, 290, 58, 18))
        self.label_12.setFont(font)
        self.memory.raise_()
        self.frame_2.raise_()
        self.program_counter.raise_()
        self.frame_3.raise_()
        self.index_x.raise_()
        self.index_y.raise_()
        self.stack_pointer.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.line.raise_()
        self.label_7.raise_()
        self.label_4.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.frame_4.raise_()
        self.label_12.raise_()
        self.textEdit = QTextEdit(self.centralwidget)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(820, 10, 270, 780))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1100, 23))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuControl = QMenu(self.menubar)
        self.menuControl.setObjectName(u"menuControl")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuControl.menuAction())
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuView.addAction(self.actionHex)
        self.menuView.addAction(self.actionDec)
        self.menuView.addSeparator()
        self.menuControl.addAction(self.actionRun)
        self.menuControl.addAction(self.actionStop)
        self.menuControl.addAction(self.actionStep)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionHex.setText(QCoreApplication.translate("MainWindow", u"Hex", None))
        self.actionDec.setText(QCoreApplication.translate("MainWindow", u"Dec", None))
        self.actionRun.setText(QCoreApplication.translate("MainWindow", u"Run", None))
        self.actionStep.setText(QCoreApplication.translate("MainWindow", u"Step", None))
        self.actionStop.setText(QCoreApplication.translate("MainWindow", u"Stop", None))
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Load ...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSave_as.setText(QCoreApplication.translate("MainWindow", u"Save as ...", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Stack Pointer", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Index X", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Index Y", None))
        self.label_page.setText(QCoreApplication.translate("MainWindow", u"Page", None))
        self.label_data.setText(QCoreApplication.translate("MainWindow", u"Data", None))
        self.page_col_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.page.setText(QCoreApplication.translate("MainWindow", u"FF", None))
        self.data.setText(QCoreApplication.translate("MainWindow", u"FF", None))
        self.page_col_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.page_col_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.page_col_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.page_col_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.page_col_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.page_col_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.page_col_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.page_col_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.page_col_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.page_col_A.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.page_col_B.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.page_col_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.page_col_D.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.page_col_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.page_col_F.setText(QCoreApplication.translate("MainWindow", u"f", None))
        self.page_row_0.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.page_row_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.page_row_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.page_row_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.page_row_4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.page_row_5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.page_row_6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.page_row_7.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.page_row_8.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.page_row_9.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.page_row_A.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.page_row_B.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.page_row_C.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.page_row_E.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.page_row_F.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.page_row_D.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"N V - B D Z C", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Program Counter", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Accumulator", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Memory", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Status Register", None))
        self.cycle_counter.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Cycles", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuControl.setTitle(QCoreApplication.translate("MainWindow", u"Control", None))
    # retranslateUi

